---
settings:
  name: StorageGRID 11.7
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: true
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: StorageGRID 11.7 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes/index.html"
  - title: 시작하십시오
    entries:
    - section: primer
    - section: network
    - title: StorageGRID를 빠르게 시작합니다
      url: "/primer/quick-start.html"
  - title: 설치 및 업그레이드
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: 구성 및 관리
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: StorageGRID를 사용합니다
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: 모니터링하고 문제를 해결합니다
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: 유지 관리
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: StorageGRID를 활성화합니다
    url: "/storagegrid-enable.html"
  - title: 이전 버전
    url: "/earlier-versions.html"
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 릴리스 정보
      url: "/release-notes/index.html"
    - title: 새로운 소식
      url: "/upgrade/whats-new.html"
    - title: StorageGRID에 대해 자세히 알아보십시오
      url: "/primer/index.html"
    - title: 네트워킹 지침
      url: "/network/index.html"
    - title: StorageGRID 빠른 시작
      url: "/primer/quick-start.html"
  - title: 하드웨어 설치 및 유지 관리
    links:
    - title: 어플라이언스 설치 및 배포
      url: "/installconfig/index.html"
    - title: 어플라이언스 유지보수
      url: "/maintain/index.html"
  - title: 소프트웨어 설치 및 업그레이드
    links:
    - title: Red Hat Enterprise Linux 또는 CentOS를 설치합니다
      url: "/rhel/index.html"
    - title: Ubuntu 또는 Debian을 설치합니다
      url: "/ubuntu/index.html"
    - title: VMware를 설치합니다
      url: "/vmware/index.html"
    - title: 소프트웨어 업그레이드
      url: "/upgrade/index.html"
  - title: 그리드를 구성합니다
    links:
    - title: StorageGRID 관리
      url: "/admin/index.html"
    - title: ILM을 사용하여 개체를 관리합니다
      url: "/ilm/index.html"
    - title: 시스템 강화
      url: "/harden/index.html"
    - title: FabricPool용 StorageGRID를 구성합니다
      url: "/fabricpool/index.html"
  - title: 개체 관리
    links:
    - title: 테넌트 계정을 사용합니다
      url: "/tenant/index.html"
    - title: S3 REST API 사용
      url: "/s3/index.html"
    - title: Swift REST API 사용(더 이상 사용 안 함)
      url: "/swift/index.html"
  - title: 모니터링 및 유지 관리
    links:
    - title: 모니터링
      url: "/monitor/index.html"
    - title: 문제 해결
      url: "/troubleshoot/index.html"
    - title: 감사 로그를 검토합니다
      url: "/audit/index.html"
    - title: 그리드를 확장합니다
      url: "/expand/index.html"
    - title: 복구 및 유지 관리
      url: "/maintain/index.html"
  - title: 데모 및 자습서
    links:
    - title: StorageGRID를 활성화하는 방법을 알아보십시오
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: StorageGRID 비디오 라이브러리
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: NetApp 학습 서비스
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: 더 많은 리소스
    links:
    - title: StorageGRID 지원 페이지
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: NetApp 상호 운용성 매트릭스 툴(IMT)
      url: https://imt.netapp.com/matrix/#welcome
    - title: StorageGRID 기술 자료
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: NetApp 블로그
      url: https://netapp.com/blog/
    - title: NetApp 커뮤니티
      url: https://community.netapp.com/
  - title: 이전 버전
    links:
    - title: StorageGRID 11.6 문서
      url: https://docs.netapp.com/us-en/storagegrid-116/index.html
    - title: StorageGRID 11.5 문서
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: StorageGRID 11.4 문서
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: StorageGRID 11.3 문서
      url: https://docs.netapp.com/sgws-113/index.jsp
