---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api 
summary: StorageGRID 11.7은 그리드 관리 API 버전 3을 사용합니다. 버전 3은 버전 2를 사용하지 않지만 버전 1과 버전 2는 계속 지원됩니다. 
---
= Grid Management API 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.7은 그리드 관리 API 버전 3을 사용합니다. 버전 3은 버전 2를 사용하지 않지만 버전 1과 버전 2는 계속 지원됩니다.


IMPORTANT: StorageGRID 11.7과 함께 관리 API 버전 1 및 버전 2를 계속 사용할 수 있지만 이러한 API 버전에 대한 지원은 StorageGRID의 향후 릴리스에서 제거됩니다. StorageGRID 11.7로 업그레이드한 후 를 사용하여 더 이상 사용되지 않는 v1 및 v2 API를 비활성화할 수 있습니다 `PUT /grid/config/management` API를 참조하십시오.

자세한 내용은 를 참조하십시오 link:../admin/using-grid-management-api.html["Grid Management API를 사용합니다"].



== 이제 노드 상태 요청에 대한 응답에 이름이 포함됩니다

신규 관련 link:../maintain/rename-grid-site-node-overview.html["그리드, 사이트 및 노드 이름 바꾸기 절차"]사이트 또는 노드의 이름을 변경한 후에는 항목의 이름(시스템 이름)과 표시 이름이 모두 * node-health * API에서 반환됩니다.



== 새 S3 테넌트의 버킷 및 액세스 키를 생성할 수 있습니다

신규 `s3Bucket` 및 `s3AccessKey` 계정 * API에 옵션이 추가되었습니다. Grid Management API를 사용하여 S3 테넌트 계정을 생성할 때 필요에 따라 해당 테넌트의 버킷뿐만 아니라 테넌트의 루트 사용자에 대한 액세스 키 ID 및 암호 키를 생성할 수 있습니다.



== 스토리지 노드의 스토리지 상태를 변경할 수 있습니다

새로운 * 노드-스토리지-상태 * API 엔드포인트를 사용하여 스토리지 노드(온라인, 오프라인, 읽기 전용)의 스토리지 상태를 확인하고 변경할 수 있습니다.
