---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 업그레이드 중에 StorageGRID 시스템이 어떻게 영향을 받는지 알아야 합니다. 
---
= 업그레이드 중 시스템에 미치는 영향
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 중에 StorageGRID 시스템이 어떻게 영향을 받는지 알아야 합니다.



== StorageGRID 업그레이드는 무중단으로 수행할 수 있습니다

StorageGRID 시스템은 업그레이드 프로세스 전반에서 클라이언트 애플리케이션의 데이터를 수집하고 검색할 수 있습니다. 같은 유형의 모든 노드를 업그레이드(예: 스토리지 노드)하도록 승인하면 노드가 한 번에 하나씩 중단되므로 특정 유형의 모든 그리드 노드 또는 모든 그리드 노드를 사용할 수 없게 되는 시간은 없습니다.

지속적인 가용성을 보장하기 위해 ILM 정책에 각 개체의 여러 복사본을 저장하도록 지정하는 규칙이 포함되어 있는지 확인합니다. 또한 모든 외부 S3 또는 Swift 클라이언트가 다음 중 하나로 요청을 보내도록 구성되어 있는지 확인해야 합니다.

* 고가용성(HA) 그룹 가상 IP 주소입니다
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대해 여러 게이트웨이 노드가 있습니다
* 각 클라이언트에 대해 여러 스토리지 노드




== 어플라이언스 펌웨어가 업그레이드되었습니다

StorageGRID 11.7 업그레이드 중:

* 모든 StorageGRID 어플라이언스 노드는 StorageGRID 어플라이언스 설치 관리자 펌웨어 버전 3.7로 자동 업그레이드됩니다.
* SG6060 및 SGF6024 어플라이언스는 BIOS 펌웨어 버전 3B07.EX 및 BMC 펌웨어 버전 3.97.07로 자동 업그레이드됩니다.
* SG100 및 SG1000 어플라이언스는 BIOS 펌웨어 버전 3B12.EC 및 BMC 펌웨어 버전 4.71.07로 자동 업그레이드됩니다.




== 알림이 트리거될 수 있습니다

서비스가 시작 및 중지되거나 StorageGRID 시스템이 혼합 버전 환경으로 작동 중일 때(이전 버전을 실행하는 일부 그리드 노드와 이후 버전으로 업그레이드된 경우) 경고가 트리거될 수 있습니다. 업그레이드가 완료된 후 다른 알림이 트리거될 수 있습니다.

예를 들어, 서비스가 중지되었을 때 * 노드 * 와 통신할 수 없음 경고가 표시되거나 일부 노드가 StorageGRID 11.7로 업그레이드되었지만 다른 노드가 여전히 StorageGRID 11.6을 실행 중일 때 * Cassandra 통신 오류 * 경고가 표시될 수 있습니다. 일반적으로 이러한 알림은 업그레이드가 완료되면 지워집니다.

StorageGRID 11.7로 업그레이드하는 동안 스토리지 노드를 중지할 때 * ILM 배치를 달성 불가능한 * 경고가 트리거될 수 있습니다. 이 알림은 업그레이드가 완료된 후 1일 동안 지속될 수 있습니다.

업그레이드가 완료된 후 Grid Manager 대시보드에서 * Recently Resolved alerts * 또는 * Current alerts * 를 선택하여 업그레이드 관련 경고를 검토할 수 있습니다.



== 많은 SNMP 알림이 생성됩니다

업그레이드 중에 그리드 노드를 중지하고 다시 시작할 때 많은 수의 SNMP 알림이 생성될 수 있습니다. 과도한 알림을 방지하려면 업그레이드를 시작하기 전에 SNMP 알림을 비활성화하려면 * SNMP 에이전트 알림 활성화 * 확인란(* 구성 * > * 모니터링 * > * SNMP 에이전트 *)을 선택 취소합니다. 그런 다음 업그레이드가 완료된 후 알림을 다시 활성화합니다.



== 구성 변경이 제한됩니다


NOTE: 이 목록은 특히 StorageGRID 11.6에서 StorageGRID 11.7로의 업그레이드에 적용됩니다. 다른 StorageGRID 릴리즈로 업그레이드하는 경우 해당 릴리즈의 업그레이드 지침에 있는 제한된 변경 사항 목록을 참조하십시오.

새 기능 사용 * 작업이 완료될 때까지 다음을 수행합니다.

* 그리드 구성을 변경하지 마십시오.
* 새 기능을 사용하거나 사용하지 않도록 설정하지 마십시오. 예를 들어, 두 StorageGRID 시스템이 모두 StorageGRID 11.7로 업데이트될 때까지 그리드 페더레이션 연결을 생성하지 마십시오.
* ILM 구성을 업데이트하지 마십시오. 그렇지 않으면 일관되지 않고 예기치 않은 ILM 동작이 발생할 수 있습니다.
* 핫픽스를 적용하거나 그리드 노드를 복구하지 마십시오.
+

NOTE: 업그레이드 중에 노드를 복구해야 하는 경우 기술 지원 부서에 문의하십시오.

* StorageGRID 11.7로 업그레이드하는 동안에는 HA 그룹, VLAN 인터페이스 또는 로드 밸런서 끝점을 관리할 수 없습니다.
* StorageGRID 11.7로의 업그레이드가 완료될 때까지 HA 그룹을 삭제하지 마십시오. 다른 HA 그룹의 가상 IP 주소에 액세스하지 못할 수 있습니다.


최종 업그레이드 단계 * 작업이 완료될 때까지:

* 확장 절차를 수행하지 마십시오.
* 서비스 해제 절차를 수행하지 마십시오.




== 테넌트 관리자에서 버킷 세부 정보를 보거나 버킷을 관리할 수 없습니다

StorageGRID 11.7로 업그레이드하는 동안(즉, 시스템이 혼합 버전 환경으로 작동하는 동안), 버킷 세부 정보를 보거나 테넌트 관리자를 사용하여 버킷을 관리할 수 없습니다. Tenant Manager의 Bucket 페이지에 다음 오류 중 하나가 나타납니다.

* 11.7로 업그레이드하는 동안에는 이 API를 사용할 수 없습니다.
* 11.7로 업그레이드하는 동안에는 테넌트 관리자에서 버킷 버전 세부 정보를 볼 수 없습니다.


11.7로의 업그레이드가 완료된 후 이 오류가 해결됩니다.

.해결 방법
11.7 업그레이드가 진행 중인 동안 테넌트 관리자를 사용하는 대신 다음 툴을 사용하여 버킷 세부 정보를 보거나 버킷을 관리합니다.

* 버킷에서 표준 S3 작업을 수행하려면 중 하나를 사용합니다 link:../s3/operations-on-buckets.html["S3 REST API"] 또는 을 누릅니다 link:../tenant/understanding-tenant-management-api.html["테넌트 관리 API"].
* 버킷에 대한 StorageGRID 사용자 지정 작업(예: 버킷 정합성 보장 수준 보기 및 수정, 마지막 액세스 시간 업데이트 활성화 또는 비활성화, 검색 통합 구성)을 수행하려면 테넌트 관리 API를 사용합니다.




== TLS 암호 또는 SSH 구성이 변경될 수 있습니다

TLS 암호 또는 SSH 구성이 수동으로 변경되었거나 노드 간에 일관성이 없는 경우 업그레이드 후 모든 노드를 레거시 호환성 또는 최신 호환성으로 덮어씁니다. 를 사용한 경우 `fips-ciphers.sh` StorageGRID 11.6에서는 일반 조건 정책이 모든 노드에 적용됩니다. 그렇지 않으면 레거시 호환성 정책이 적용됩니다. 일반 조건 검증 구성이 필요한 경우 일반 조건 정책 또는 FIPS 엄격한 정책을 사용해야 합니다. 를 사용하지 않은 경우 `fips-ciphers.sh`업그레이드가 완료된 후 새로운 최신 호환성 설정을 사용해야 합니다. 암호를 구성하려면 * 구성 * > * 보안 * > * 보안 설정 * 으로 이동하여 * TLS 및 SSH 정책 * 을 선택합니다.



== CLB 포트는 로드 밸런서 끝점으로 변환될 수 있습니다

레거시 연결 로드 밸런서(CLB) 서비스가 StorageGRID 11.7에서 제거되었습니다. 업그레이드 사전 점검 중에 CLB 구성이 감지되면 * 레거시 CLB 로드 밸런서 활동이 감지됨 * 경고가 트리거됩니다. 기존 StorageGRID 버전에서 S3 또는 Swift API에 대해 사용자 지정 인증서가 설정된 경우, StorageGRID 11.7로 업그레이드하는 동안 CLB 포트 8082, 8083, 8084 및 8085가 로드 엔드포인트 밸런서로 변환됩니다.

도 참조하십시오 link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"].
