---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.7 
summary: 이번 StorageGRID 릴리즈에는 다음과 같은 기능이 도입되었습니다. 
---
= StorageGRID 11.7의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 StorageGRID 릴리스는 다음과 같은 기능 및 기능 변경 사항을 소개합니다.



== 새로운 기능



=== 그리드 통합

두 StorageGRID 시스템 간의 그리드 페더레이션 연결을 구성하여 테넌트 계정 정보를 복제하고 재해 복구를 위해 그리드 간에 버킷 객체를 복제할 수 있습니다. 을 참조하십시오 link:../admin/grid-federation-overview.html["그리드 페더레이션은 무엇입니까?"], link:../admin/grid-federation-what-is-account-clone.html["계정 클론이란 무엇입니까"], 및 link:../admin/grid-federation-what-is-cross-grid-replication.html["크로스 그리드 복제란"].



=== 읽기 가용성 향상

읽기-쓰기 후-쓰기(기본값) 일관성 제어가 더욱 가용성되도록 개선되었습니다. 존재하지 않는 객체에 대한 GET/HEAD 요청은 각 사이트에서 최대 1개의 스토리지 노드를 오프라인 상태로 성공하게 됩니다. 이 시나리오에서는 버킷을 더 이상 사용 가능한 정합성 제어기로 설정할 필요가 없습니다. 예를 들어, 생성하기 전에 개체의 존재를 확인하는 애플리케이션은 스토리지 노드 하나가 오프라인일 때 소프트웨어 업그레이드 중에도 새 쓰기 후 읽기 기능을 사용하여 제대로 작동합니다.



=== 그리드, 사이트 및 노드의 이름을 바꿉니다

새로운 유지보수 절차를 통해 그리드 관리자 전체에 표시되는 표시 이름을 변경할 수 있습니다. 필요할 때마다 표시 이름을 안전하게 업데이트할 수 있습니다. 을 참조하십시오 link:../maintain/rename-grid-site-node-overview.html["그리드, 사이트 및 노드의 이름을 바꿉니다"].



=== FabricPool 및 S3 설정 마법사

FabricPool 및 S3 설정 마법사는 ONTAP FabricPool 또는 다른 S3 클라이언트 응용 프로그램에서 사용할 StorageGRID를 구성하는 각 단계를 안내하고 다른 응용 프로그램에 필요한 값을 입력할 때 사용할 수 있는 파일을 생성합니다. 을 참조하십시오 link:../fabricpool/use-fabricpool-setup-wizard.html["FabricPool 설정 마법사를 사용합니다"] 및 link:../admin/use-s3-setup-wizard.html["S3 설정 마법사를 사용합니다"].

이 변경 사항과 관련하여 새 사용자에게 구성할 것을 알리는 배너가 대시보드에 표시됩니다 link:../admin/configuring-s3-api-endpoint-domain-names.html["S3 끝점 도메인 이름"] S3 가상 호스팅 방식의 요청 및 설정 link:../monitor/email-alert-notifications.html["알림에 대한 이메일 알림입니다"].



=== 방화벽 제어

방화벽 제어 페이지에서는 그리드에 있는 노드의 포트에 대한 외부 액세스를 관리하고 닫힌 포트에 대한 액세스가 허용되는 호스트 주소 및 IP 서브넷을 정의할 수 있습니다. 새 페이지에는 신뢰할 수 없는 클라이언트 네트워크 설정도 포함되어 있어 신뢰할 수 없는 클라이언트 네트워크가 구성될 때 열려는 추가 포트를 선택할 수 있습니다. 을 참조하십시오 link:../admin/configure-firewall-controls.html["내부 방화벽을 구성합니다"].



=== 향상된 보안 정책

이제 클라이언트 응용 프로그램과 보안 TLS 연결을 설정하고 내부 StorageGRID 서비스에 대한 보안 SSH 연결을 설정하는 데 사용되는 프로토콜과 암호를 결정할 수 있습니다. 을 참조하십시오 link:../admin/manage-tls-ssh-policy.html["TLS 및 SSH 정책을 관리합니다"].



=== 부하 분산 장치 엔드포인트 변경

시기 link:../admin/configuring-load-balancer-endpoints.html["부하 분산 장치 엔드포인트 구성"]이제 다음을 수행할 수 있습니다.

* 모든 테넌트가 엔드포인트에 액세스할 수 있도록 허용(기본값) 또는 테넌트와 해당 엔드포인트 간의 보안 격리를 개선할 수 있도록 허용 또는 차단된 테넌트 목록을 지정합니다.
* 노드 유형 * 바인딩 모드를 사용하면 클라이언트가 선택한 노드 유형에 따라 관리 노드의 IP 주소(또는 해당 FQDN)나 게이트웨이 노드의 IP 주소를 사용하도록 할 수 있습니다.




== SGF6112 All-Flash 어플라이언스

새로운 StorageGRID SGF6112 스토리지 어플라이언스는 컴퓨팅 컨트롤러와 스토리지 컨트롤러를 1U 섀시에 통합하는 콤팩트한 설계를 특징으로 합니다. 어플라이언스는 드라이브당 최대 15.3TB의 저장 용량을 가진 12개의 SSD NVMe 드라이브를 지원합니다. SSD 드라이브는 복원력이 뛰어난 오브젝트 스토리지를 제공하는 RAID에 있습니다. 을 참조하십시오 link:../installconfig/hardware-description-sg6100.html["SGF6112 어플라이언스: 개요"].



== 기타 그리드 관리자 기능 향상



=== ILM의 개선 사항

향상된 ILM 마법사를 사용하면 필터를 지정하고, 기간 및 배치를 입력하고, 보존 다이어그램을 볼 수 있습니다. 삭제 코딩 프로필은 배치를 위해 스토리지 풀과 EC 스키마를 선택할 때 자동으로 생성됩니다. 새 StorageGRID 11.7 설치(업그레이드 아님)의 경우 각 사이트에 대해 스토리지 풀이 자동으로 생성되고 새 * 사이트당 1개 복사 * 기본 규칙을 사용하면 새로운 다중 사이트 설치에 사이트 손실 보호가 기본적으로 적용됩니다. 을 참조하십시오 link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"].



=== 맞춤형 대시보드

이제 Grid Manager에 대한 사용자 지정 대시보드를 구성할 수 있습니다. 을 참조하십시오 link:../monitor/viewing-dashboard.html["대시보드를 보고 관리합니다"].



=== 볼륨 복원 UI

스토리지 볼륨 복원 기능을 사용하면 스토리지 볼륨에 장애가 발생할 경우 오브젝트 데이터를 복원할 수 있습니다. StorageGRID 11.7의 경우 수동으로 명령을 입력하는 기존 방법 외에도 그리드 관리자에서 볼륨 복원을 시작할 수 있습니다. 이제 그리드 관리자를 사용하는 것이 개체 데이터를 복원하는 기본 방법입니다. 을 참조하십시오 link:../maintain/restoring-volume.html["Grid Manager를 사용하여 개체 데이터를 복원합니다"].



=== 업그레이드 및 핫픽스 UI

StorageGRID 11.7로 업그레이드할 때 최신 11.7 핫픽스를 동시에 적용할 수 있습니다. StorageGRID 업그레이드 페이지에는 권장 업그레이드 경로와 올바른 다운로드 페이지로 직접 연결되는 링크가 표시됩니다. 을 참조하십시오 link:performing-upgrade.html["업그레이드를 수행합니다"].



=== 스토리지 값의 단위입니다

이제 Grid Manager 및 Tenant Manager에 표시되는 스토리지 값에 대해 기본 10 또는 기본 2 단위를 선택할 수 있습니다. Grid Manager 또는 Tenant Manager의 오른쪽 상단에서 사용자 드롭다운을 선택한 다음 * User preferences * 를 선택합니다.



=== Grid Manager에서 MIB에 액세스합니다

이제 SNMP 에이전트 페이지를 사용하여 Grid Manager에서 SNMP 호환 MIB 파일에 액세스할 수 있습니다. 을 참조하십시오 link:../monitor/access-snmp-mib.html["MIB 파일에 액세스합니다"].



=== 새 노드의 사용자 지정 스토리지 평점

확장을 수행하여 새 사이트 또는 새 스토리지 노드를 추가할 때 이제 각 새 노드에 사용자 지정 스토리지 등급을 할당할 수 있습니다. 을 참조하십시오 link:../expand/performing-expansion.html["확장을 수행합니다"].



== 테넌트 관리자 업데이트



=== 교차 그리드 복제

를 사용할 수 있는 권한이 있는 테넌트 계정입니다 <<grid-federation,그리드 페더레이션 연결>> 테넌트 그룹, 사용자 및 S3 키를 한 그리드에서 다른 그리드로 복제하고 크로스 그리드 복제를 사용하여 두 그리드 간에 버킷 오브젝트를 복제할 수 있습니다. 을 참조하십시오 link:../tenant/grid-federation-account-clone.html["클론 테넌트 그룹 및 사용자"] 및 link:../tenant/grid-federation-manage-cross-grid-replication.html["교차 그리드 복제 관리"].



=== 버킷에서 모든 오브젝트를 삭제합니다

이제 테넌트 관리자 사용자가 버킷의 모든 오브젝트를 삭제할 수 있으므로 버킷을 삭제할 수 있습니다. 을 참조하십시오 link:../tenant/deleting-s3-bucket-objects.html["버킷에서 오브젝트를 삭제합니다"].



=== S3 오브젝트 잠금 기본 보존

이제 테넌트 관리자 사용자는 S3 오브젝트 잠금 버킷을 생성할 때 기본 보존을 설정하고 구성할 수 있습니다. 을 참조하십시오 link:../tenant/creating-s3-bucket.html["S3 버킷을 생성합니다"].



== S3 업데이트



=== S3 오브젝트 잠금 거버넌스 모드

오브젝트에 대한 S3 오브젝트 잠금 설정 또는 버킷의 기본 보존 설정을 지정할 때 이제 거버넌스 모드를 사용할 수 있습니다. 이 보존 모드를 사용하면 특정 보존 설정을 무시할 수 있는 특별한 권한이 있는 사용자가 있습니다. 을 참조하십시오 link:../tenant/using-s3-object-lock.html["S3 오브젝트 잠금을 사용하여 오브젝트를 보존합니다"] 및 link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 오브젝트 잠금을 구성합니다"].



=== 랜섬웨어 완화를 위한 S3 그룹 정책

S3 테넌트 계정에 대한 그룹 정책으로 추가된 샘플 정책은 랜섬웨어 공격을 완화하는 데 도움이 됩니다. 이전 개체 버전이 영구적으로 삭제되지 않도록 합니다. 을 참조하십시오 link:../tenant/creating-groups-for-s3-tenant.html["S3 테넌트에 대한 그룹을 생성합니다"].



=== S3 버킷을 위한 NewerNoncurrentVersions 임계값입니다

를 클릭합니다 `NewerNoncurrentVersions` 버킷 수명 주기 구성의 작업은 버전 관리가 된 S3 버킷에 유지되는 비현재 버전의 수를 지정합니다. 이 임계값은 ILM에서 제공하는 수명 주기 규칙보다 우선합니다. 을 참조하십시오 link:../ilm/how-objects-are-deleted.html["오브젝트 삭제 방법"].



=== S3 업데이트 를 선택합니다

S3 SelectObjectContent는 이제 Parquet 객체에 대한 지원을 제공합니다. 또한 이제 cgroup v2가 활성화된 커널을 실행하는 베어 메탈 노드인 Admin 및 Gateway 부하 분산 엔드포인트와 함께 S3 Select를 사용할 수 있습니다. 을 참조하십시오 link:../s3/select-object-content.html["S3 SelectObjectContent"].



== 기타 향상된 기능



=== 인증서 주체 선택 사항입니다

이제 인증서 주체 필드는 선택 사항입니다. 이 필드를 비워 두면 생성된 인증서는 첫 번째 도메인 이름 또는 IP 주소를 CN(Subject Common Name)으로 사용합니다. 을 참조하십시오 link:../admin/using-storagegrid-security-certificates.html["보안 인증서를 관리합니다"].



=== ILM 감사 메시지 범주 및 새 메시지

ILM 작업을 위해 감사 메시지 범주가 추가되었으며 IDEL, LKCU 및 ORLM 메시지가 포함됩니다. 이 새 범주는 * Normal * 로 설정됩니다. 을 참조하십시오 link:../audit/ilm-audit-messages.html["ILM 운영 감사 메시지"].

또한 새 11.7 기능을 지원하기 위해 새 감사 메시지가 추가되었습니다.

* link:../audit/bror-bucket-read-only-request.html["BROR: 버킷 읽기 전용 요청"]
* link:../audit/cgrr-cross-grid-replication-request.html["CGRR: 교차 그리드 복제 요청"]
* link:../audit/ebdl-empty-bucket-delete.html["EBDL: 빈 버킷 삭제"]
* link:../audit/ebkr-empty-bucket-request.html["EBKR: 빈 버킷 요청"]
* link:../audit/s3-select-request.html["S3SL:S3 요청 선택"]




=== 새 경고

StorageGRID 11.7에 대해 다음과 같은 새 경고가 추가되었습니다.

* 어플라이언스 DAS 드라이브 장애가 감지되었습니다
* 어플라이언스 DAS 드라이브 재구축
* 어플라이언스 팬 장애가 감지되었습니다
* 어플라이언스 NIC 장애가 감지되었습니다
* 어플라이언스 SSD 위험 경고
* AutoSupport 메시지를 보내지 못했습니다
* Cassandra 크기 초과 쓰기 오류입니다
* 교차 그리드 복제 영구 요청 실패
* 교차 그리드 복제 리소스를 사용할 수 없습니다
* 디버그 성능 영향
* 그리드 페더레이션 인증서의 만료
* FabricPool 버킷은 버킷 정합성 설정을 지원하지 않습니다
* 방화벽 구성 실패
* 그리드 페더레이션 연결에 실패했습니다
* 스토리지 어플라이언스 팬 장애가 감지되었습니다
* 스토리지 노드가 원하는 스토리지 상태가 아닙니다
* 스토리지 볼륨에 주의가 필요합니다
* 스토리지 볼륨을 복원해야 합니다
* 스토리지 볼륨이 오프라인 상태입니다
* 추적 구성이 활성화되었습니다
* 볼륨 복원에서 복제된 데이터 복구를 시작하지 못했습니다




=== 문서 변경

* 새로운 빠른 참조에는 StorageGRID이 Amazon S3(Simple Storage Service) API를 지원하는 방법이 요약되어 있습니다. 을 참조하십시오 link:../s3/quick-reference-support-for-aws-apis.html["빠른 참조: 지원되는 S3 API 요청"].
* 새로운 소식 link:../primer/quick-start.html["StorageGRID 빠른 시작"] 에는 StorageGRID 시스템을 구성 및 사용하기 위한 고급 단계가 나와 있으며 관련 지침에 대한 링크를 제공합니다.
* 어플라이언스 하드웨어 설치 지침은 사용 편의성을 위해 결합되고 통합되었습니다. 빠른 시작이 하드웨어 설치에 대한 고급 가이드로 추가되었습니다. 을 참조하십시오link:../installconfig/index.html["하드웨어 설치를 빠르게 시작합니다"].
* 모든 어플라이언스 모델에 공통되는 유지보수 지침은 통합 및 통합되어 있으며 문서 사이트의 유지 관리 섹션으로 이동되었습니다. 을 참조하십시오 link:../commonhardware/index.html["공통 노드 유지 관리: 개요"].
* 각 어플라이언스 모델별 유지보수 지침도 유지보수 섹션으로 이동했습니다.
+
link:../sg6100/index.html["SGF6112 하드웨어를 유지보수하십시오"]

+
link:../sg6000/index.html["SG6000 하드웨어 유지보수"]

+
link:../sg5700/index.html["SG5700 하드웨어 유지 관리"]

+
link:../sg100-1000/index.html["SG100 및 SG1000 하드웨어를 유지보수하십시오"]


