---
permalink: installconfig/gathering-installation-information-sg5700.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, install, information, site, pre-install, preparing, prepare, preinstall, info, preparation 
summary: 표를 사용하여 어플라이언스에 연결하는 각 네트워크에 필요한 정보를 기록합니다. 이러한 값은 하드웨어를 설치하고 구성하는 데 필요합니다. 
---
= 설치 정보 수집(SG5700)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
표를 사용하여 어플라이언스에 연결하는 각 네트워크에 필요한 정보를 기록합니다. 이러한 값은 하드웨어를 설치하고 구성하는 데 필요합니다.


TIP: 표를 사용하는 대신 ConfigBuilder와 함께 제공된 통합 문서를 사용합니다. ConfigBuilder 통합 문서를 사용하면 시스템 정보를 업로드하고 JSON 파일을 생성하여 StorageGRID 어플라이언스 설치 프로그램에서 일부 구성 단계를 자동으로 완료할 수 있습니다. 을 참조하십시오 link:automating-appliance-installation-and-configuration.html["어플라이언스 설치 및 구성 자동화"].



== E2800 컨트롤러의 SANtricity System Manager에 연결하는 데 필요한 정보입니다

E2800 시리즈 컨트롤러는 SANtricity 시스템 관리자에 사용할 관리 네트워크에 연결됩니다.

[cols="2a,1a"]
|===
| 정보가 필요합니다 | 귀사의 가치 


 a| 
관리 포트 1에 연결할 이더넷 스위치 포트
 a| 



 a| 
관리 포트 1의 MAC 주소(포트 P1 근처의 레이블에 인쇄되어 있음)
 a| 



 a| 
전원을 켠 후 사용할 수 있는 경우 관리 포트 1에 대해 DHCP 할당 IP 주소입니다

* 참고: * E2800 컨트롤러에 연결할 네트워크에 DHCP 서버가 포함된 경우 네트워크 관리자는 MAC 주소를 사용하여 DHCP 서버에서 할당한 IP 주소를 확인할 수 있습니다.
 a| 



 a| 
속도 및 이중 모드

* 참고: * SANtricity 시스템 관리자 관리 네트워크의 이더넷 스위치가 자동 교섭으로 설정되어 있는지 확인해야 합니다.
 a| 
반드시:

* 자동 협상(기본값)




 a| 
IP 주소 형식입니다
 a| 
다음 중 하나를 선택하십시오.

* IPv4
* IPv6




 a| 
관리 네트워크에서 어플라이언스에 사용할 고정 IP 주소입니다
 a| 
IPv4의 경우:

* IPv4 주소:
* 서브넷 마스크:
* 게이트웨이:


IPv6의 경우:

* IPv6 주소:
* 라우팅 가능한 IP 주소:
* E2800 컨트롤러 라우터 IP 주소:


|===


== E700SG 컨트롤러를 관리 네트워크에 연결하는 데 필요한 정보입니다

StorageGRID용 관리 네트워크는 시스템 관리 및 유지 보수에 사용되는 선택적 네트워크입니다. 어플라이언스는 E5500SG 컨트롤러의 1GbE 관리 포트를 사용하여 관리 네트워크에 연결됩니다.

[cols="2a,1a"]
|===
| 정보가 필요합니다 | 귀사의 가치 


 a| 
관리자 네트워크가 활성화되었습니다
 a| 
다음 중 하나를 선택하십시오.

* 아니요
* 예(기본값)




 a| 
네트워크 연결 모드
 a| 
다음 중 하나를 선택하십시오.

* 독립적입니다
* Active - 백업




 a| 
포트 1의 스위치 포트
 a| 



 a| 
포트 2용 스위치 포트(Active-Backup 네트워크 연결 모드만 해당)
 a| 



 a| 
전원을 켠 후 사용할 수 있는 경우 관리 포트 1에 대해 DHCP 할당 IP 주소입니다

* 참고: * 관리 네트워크에 DHCP 서버가 포함된 경우, E700SG 컨트롤러는 부팅 후 7개 세그먼트 디스플레이에 DHCP 할당 IP 주소를 표시합니다. MAC 주소를 사용하여 할당된 IP를 조회하여 DHCP 할당 IP 주소를 확인할 수도 있습니다.
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:




 a| 
관리 네트워크의 어플라이언스 스토리지 노드에 사용할 고정 IP 주소입니다

* 참고: * 네트워크에 게이트웨이가 없는 경우 게이트웨이에 대해 동일한 정적 IPv4 주소를 지정합니다.
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:




 a| 
관리 네트워크 서브넷(CIDR)
 a| 

|===


== E5500SG 컨트롤러에서 10/25-GbE 포트를 연결 및 구성하는 데 필요한 정보입니다

E5500SG 컨트롤러에 있는 4개의 10/25-GbE 포트는 StorageGRID 그리드 네트워크 및 클라이언트 네트워크에 연결됩니다.


NOTE: 을 참조하십시오 link:port-bond-modes-for-e5700sg-controller-ports.html["포트 결합 모드(E5500SG 컨트롤러)"].

[cols="2a,1a"]
|===
| 정보가 필요합니다 | 귀사의 가치 


 a| 
링크 속도

* 참고: * 25GbE를 선택한 경우 SPF28 트랜시버를 설치합니다. 자동 협상은 지원되지 않으므로 25GbE 포트 및 연결된 스위치도 구성해야 합니다.
 a| 
다음 중 하나를 선택하십시오.

* 10GbE(기본값)
* 25GbE




 a| 
포트 결합 모드
 a| 
다음 중 하나를 선택하십시오.

* 고정(기본값)
* 집계




 a| 
포트 1용 스위치 포트(클라이언트 네트워크)
 a| 



 a| 
포트 2용 스위치 포트(그리드 네트워크)
 a| 



 a| 
포트 3용 스위치 포트(클라이언트 네트워크)
 a| 



 a| 
포트 4용 스위치 포트(그리드 네트워크)
 a| 

|===


== E700SG 컨트롤러를 그리드 네트워크에 연결하는 데 필요한 정보입니다

StorageGRID용 그리드 네트워크는 모든 내부 StorageGRID 트래픽에 사용되는 필수 네트워크입니다. 이 어플라이언스는 E5500SG 컨트롤러의 10/25-GbE 포트를 사용하여 그리드 네트워크에 연결됩니다.


NOTE: 을 참조하십시오 link:port-bond-modes-for-e5700sg-controller-ports.html["포트 결합 모드(E5500SG 컨트롤러)"].

[cols="2a,1a"]
|===
| 정보가 필요합니다 | 귀사의 가치 


 a| 
네트워크 연결 모드
 a| 
다음 중 하나를 선택하십시오.

* Active-Backup(기본값)
* LACP(802.3ad)




 a| 
VLAN 태그 지정이 활성화되었습니다
 a| 
다음 중 하나를 선택하십시오.

* 아니요(기본값)
* 예




 a| 
VLAN 태그(VLAN 태그 지정이 활성화된 경우)
 a| 
0에서 4095 사이의 값을 입력합니다.



 a| 
전원을 켠 후 사용할 수 있는 경우 그리드 네트워크에 대해 DHCP 할당 IP 주소입니다

* 참고: * 그리드 네트워크에 DHCP 서버가 포함된 경우, E700SG 컨트롤러는 부팅된 후 7세그먼트 디스플레이에 그리드 네트워크에 대해 DHCP 할당 IP 주소를 표시합니다.
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:




 a| 
그리드 네트워크에서 어플라이언스 스토리지 노드에 사용할 고정 IP 주소입니다

* 참고: * 네트워크에 게이트웨이가 없는 경우 게이트웨이에 대해 동일한 정적 IPv4 주소를 지정합니다.
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:




 a| 
그리드 네트워크 서브넷(CIDR)

* 참고: * 클라이언트 네트워크가 활성화되지 않은 경우 컨트롤러의 기본 라우트는 여기에 지정된 게이트웨이를 사용합니다.
 a| 

|===


== E700SG 컨트롤러를 클라이언트 네트워크에 연결하는 데 필요한 정보입니다

StorageGRID용 클라이언트 네트워크는 일반적으로 그리드에 대한 클라이언트 프로토콜 액세스를 제공하는 데 사용되는 선택적 네트워크입니다. 어플라이언스는 E5500SG 컨트롤러의 10/25-GbE 포트를 사용하여 클라이언트 네트워크에 연결됩니다.


NOTE: 을 참조하십시오 link:port-bond-modes-for-e5700sg-controller-ports.html["포트 결합 모드(E5500SG 컨트롤러)"].

[cols="2a,1a"]
|===
| 정보가 필요합니다 | 귀사의 가치 


 a| 
클라이언트 네트워크가 활성화되었습니다
 a| 
다음 중 하나를 선택하십시오.

* 아니요(기본값)
* 예




 a| 
네트워크 연결 모드
 a| 
다음 중 하나를 선택하십시오.

* Active-Backup(기본값)
* LACP(802.3ad)




 a| 
VLAN 태그 지정이 활성화되었습니다
 a| 
다음 중 하나를 선택하십시오.

* 아니요(기본값)
* 예




 a| 
VLAN 태그

(VLAN 태그 지정이 설정된 경우)
 a| 
0에서 4095 사이의 값을 입력합니다.



 a| 
전원을 켠 후 사용할 수 있는 경우 클라이언트 네트워크에 대해 DHCP 할당 IP 주소입니다
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:




 a| 
클라이언트 네트워크의 어플라이언스 스토리지 노드에 사용할 고정 IP 주소입니다

* 참고: * 클라이언트 네트워크가 활성화된 경우 컨트롤러의 기본 라우트는 여기에 지정된 게이트웨이를 사용합니다.
 a| 
* IPv4 주소(CIDR):
* 게이트웨이:


|===
.관련 정보
* link:sg5700-appliance-connections.html["네트워크 연결(SG5700)"]
* link:port-bond-modes-for-e5700sg-controller-ports.html["포트 결합 모드(E5500SG 컨트롤러)"]
* link:configuring-hardware.html["하드웨어 구성(SG5700)"]

