---
permalink: installconfig/viewing-boot-up-codes-for-appliance-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, boot codes, boot-up codes, start codes, codes, boot, start, bmc 
summary: 장치에 전원을 공급하면 BMC가 일련의 부팅 코드를 기록합니다. BMC 관리 포트에 연결된 그래픽 콘솔에서 이러한 코드를 볼 수 있습니다. 
---
= 부팅 코드 보기(SG100 및 SG1000)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장치에 전원을 공급하면 BMC가 일련의 부팅 코드를 기록합니다. BMC 관리 포트에 연결된 그래픽 콘솔에서 이러한 코드를 볼 수 있습니다.

.시작하기 전에
* BMC 대시보드에 액세스하는 방법을 알고 있습니다.
* SOL(Serial-over-LAN)을 사용하려는 경우 IPMI SOL 콘솔 애플리케이션을 사용하는 경험이 있습니다.


.단계
. 어플라이언스 컨트롤러의 부팅 코드를 보려면 다음 방법 중 하나를 선택하고 필요한 장비를 수집합니다.
+
[cols="1a,2a"]
|===
| 방법 | 필수 장비 


 a| 
VGA 콘솔
 a| 
** VGA 지원 모니터
** VGA 케이블




 a| 
KVM
 a| 
** RJ-45 케이블




 a| 
직렬 포트
 a| 
** DB-9 직렬 케이블
** 가상 직렬 터미널




 a| 
솔
 a| 
** 가상 직렬 터미널


|===
. VGA 콘솔을 사용하는 경우 다음 단계를 수행하십시오.
+
.. VGA 지원 모니터를 제품 뒷면의 VGA 포트에 연결합니다.
.. 모니터에 표시된 코드를 봅니다.


. BMC KVM을 사용하는 경우 다음 단계를 수행하십시오.
+
.. BMC 관리 포트에 연결하고 BMC 웹 인터페이스에 로그인합니다.
.. 리모컨 * 을 선택합니다.
.. KVM을 실행합니다.
.. 가상 모니터에서 코드를 봅니다.


. 직렬 포트 및 터미널을 사용하는 경우 다음 단계를 수행하십시오.
+
.. 어플라이언스 뒷면의 DB-9 직렬 포트에 연결합니다.
.. 설정을 사용합니다 `115200 8-N-1`.
.. 직렬 터미널에 인쇄된 코드를 봅니다.


. SOL을 사용하는 경우 다음 단계를 수행하십시오.
+
.. BMC IP 주소 및 로그인 자격 증명을 사용하여 IPMI SOL에 연결합니다.
+
`ipmitool -I lanplus -H _BMC_Port_IP_ -U admin -P _Password_ sol activate`

+

NOTE: 경우에 따라 기본 사용자 이름이 일 수 있습니다 `root` 대신 `admin`.

.. 가상 시리얼 터미널에서 코드를 봅니다.


. 표를 사용하여 제품의 코드를 찾습니다.
+
[cols="1a,3a"]
|===
| 코드 | 를 나타냅니다 


 a| 
안녕
 a| 
마스터 부트 스크립트가 시작되었습니다.



 a| 
HP
 a| 
시스템에서 네트워크 인터페이스 카드(NIC) 펌웨어를 업데이트해야 하는지 확인합니다.



 a| 
RB
 a| 
펌웨어 업데이트를 적용한 후 시스템이 재부팅되고 있습니다.



 a| 
FP
 a| 
하드웨어 하위 시스템 펌웨어 업데이트 검사가 완료되었습니다. 컨트롤러 간 통신 서비스가 시작됩니다.



 a| 
HC
 a| 
시스템에서 기존 StorageGRID 설치 데이터를 확인하고 있습니다.



 a| 
호
 a| 
StorageGRID 어플라이언스가 실행 중입니다.



 a| 
HA
 a| 
StorageGRID가 실행 중입니다.

|===


.관련 정보
link:../installconfig/accessing-bmc-interface.html["BMC 인터페이스에 액세스합니다"]
