---
permalink: swift/put-container-consistency-request.html 
sidebar: sidebar 
keywords: put container consistency request 
summary: '저장 컨테이너 일관성 요청을 사용하면 컨테이너에서 수행된 작업에 적용할 일관성 수준을 지정할 수 있습니다. 기본적으로 새 컨테이너는 "read-after-new-write" 일관성 수준을 사용하여 생성됩니다.' 
---
= 컨테이너 일관성 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
저장 컨테이너 일관성 요청을 사용하면 컨테이너에서 수행된 작업에 적용할 일관성 수준을 지정할 수 있습니다. 기본적으로 새 컨테이너는 "새 쓰기 후 다시 쓰기" 일관성 수준을 사용하여 생성됩니다.



== 요청하십시오

[cols="2a,4a"]
|===
| HTTP 헤더를 요청합니다 | 설명 


| X-Auth - 토큰  a| 
요청에 사용할 계정의 Swift 인증 토큰입니다.



| X-NTAP-sg-정합성  a| 
컨테이너의 작업에 적용할 일관성 제어 수준입니다. 지원되는 값은 다음과 같습니다.

* ALL *: 모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.

* strong-global *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

* strong-site *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

* read-after-new-write *: (기본값)는 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.

* 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.



| 호스트  a| 
요청이 전달되는 호스트 이름입니다.

|===


== 일관성 제어 및 ILM 규칙이 상호 작용하여 데이터 보호에 영향을 미치는 방식

일관성 제어와 ILM 규칙 모두 오브젝트의 보호 방법에 영향을 미칩니다. 이러한 설정은 상호 작용할 수 있습니다.

예를 들어, 개체가 저장될 때 사용되는 일관성 컨트롤은 오브젝트 메타데이터의 초기 배치에 영향을 미치는 반면 ILM 규칙에 대해 선택된 수집 동작은 오브젝트 복사본의 초기 배치에 영향을 줍니다. StorageGRID에서는 클라이언트 요청을 이행하기 위해 오브젝트의 메타데이터와 해당 데이터에 모두 액세스해야 하므로 일관성 수준과 수집 동작에 적합한 보호 수준을 선택하면 초기 데이터 보호 수준을 높이고 시스템 응답을 더욱 정확하게 예측할 수 있습니다.

ILM 규칙에 대해 다음과 같은 수집 동작을 사용할 수 있습니다.

* * Strict * : ILM 규칙에 지정된 모든 사본은 클라이언트에 반환되기 전에 만들어야 합니다.
* * 균형 *: StorageGRID는 수집 시 ILM 규칙에 지정된 모든 복제본을 생성하려고 합니다. 그렇지 않을 경우 중간 복사본이 만들어지고 클라이언트에 성공적으로 반환됩니다. ILM 규칙에 지정된 복사본은 가능한 경우 만들어집니다.
* * 이중 커밋*: StorageGRID는 즉시 개체의 임시 복사본을 만들고 클라이언트에 성공을 반환합니다. ILM 규칙에 지정된 복사본은 가능한 경우 만들어집니다.



NOTE: ILM 규칙의 수집 동작을 선택하기 전에 정보 수명 주기 관리를 통해 개체를 관리하기 위한 지침에서 이러한 설정에 대한 전체 설명을 읽어보십시오.



== 일관성 제어 및 ILM 규칙이 상호 작용하는 방법의 예

다음 ILM 규칙 및 다음 일관성 수준 설정이 있는 두 사이트 그리드가 있다고 가정합니다.

* * ILM 규칙 *: 로컬 사이트와 원격 사이트에 각각 하나씩, 두 개의 오브젝트 복사본을 만듭니다. Strict 수집 동작이 선택됩니다.
* * Consistency level *: "trong-global"(개체 메타데이터가 모든 사이트에 즉시 배포됩니다.)


클라이언트가 오브젝트를 그리드에 저장할 때 StorageGRID는 오브젝트 복사본을 둘 다 만들고 메타데이터를 두 사이트에 분산한 다음 클라이언트에 성공을 반환합니다.

수집 성공 메시지가 표시된 시점에 객체가 손실로부터 완벽하게 보호됩니다. 예를 들어, 수집 직후 로컬 사이트가 손실되면 오브젝트 데이터와 오브젝트 메타데이터의 복사본이 원격 사이트에 계속 존재합니다. 개체를 완전히 검색할 수 있습니다.

대신 동일한 ILM 규칙 및 "'strong-site' 정합성 보장 수준을 사용한 경우 객체 데이터가 원격 사이트에 복제되었지만 객체 메타데이터가 그 위치에 배포되기 전에 클라이언트에 성공 메시지가 표시될 수 있습니다. 이 경우 오브젝트 메타데이터의 보호 수준이 오브젝트 데이터의 보호 수준과 일치하지 않습니다. 수집 후 곧바로 로컬 사이트가 손실되면 오브젝트 메타데이터가 손실됩니다. 개체를 검색할 수 없습니다.

일관성 수준과 ILM 규칙 간의 상호 관계는 복잡할 수 있습니다. 도움이 필요한 경우 NetApp에 문의하십시오.



== 요청 예

[listing]
----
PUT /v1/28544923908243208806/_Swift container_
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: strong-site
Host: test.com
----


== 응답

|===
| 응답 HTTP 헤더 | 설명 


 a| 
`Date`
 a| 
응답의 날짜 및 시간입니다.



 a| 
`Connection`
 a| 
서버에 대한 연결이 열려 있는지 또는 닫혀 있는지 여부



 a| 
`X-Trans-Id`
 a| 
요청에 대한 고유한 트랜잭션 식별자입니다.



 a| 
`Content-Length`
 a| 
응답 바디의 길이.

|===


== 응답 예

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
----