---
permalink: tenant/changing-consistency-level.html 
sidebar: sidebar 
keywords: how to change bucket consistency level, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: S3 테넌트를 사용하는 경우 S3 버킷의 오브젝트에 대해 수행된 작업의 일관성 수준을 변경할 수 있습니다. 
---
= 버킷의 정합성 수준을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하는 경우 S3 버킷의 오브젝트에 대해 수행된 작업의 일관성 수준을 변경할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].
* 이 있는 사용자 그룹에 속해 있습니다 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.


.이 작업에 대해
일관성 제어를 통해 오브젝트의 가용성과 서로 다른 스토리지 노드 및 사이트 전체에서 이러한 오브젝트의 일관성 간의 균형을 유지할 수 있습니다. 일반적으로 버킷에 대해 * Read-After-new-write * 정합성 수준을 사용해야 합니다.

새 쓰기 후 읽기 * 정합성 보장 레벨이 클라이언트 애플리케이션의 요구 사항을 충족하지 않는 경우 버킷 정합성 수준을 설정하거나 을 사용하여 정합성 보장 레벨을 변경할 수 있습니다 `Consistency-Control` 머리글. 를 클릭합니다 `Consistency-Control` 헤더는 버킷 정합성 레벨을 오버라이드합니다.


NOTE: 버킷의 정합성 수준을 변경하면 변경 후 수집된 객체만 수정된 레벨에 맞게 보장됩니다.

.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 테이블에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. Bucket options * 탭에서 * Consistency level * 아코디언을 선택합니다.
. 이 버킷의 오브젝트에 대해 수행된 작업의 정합성 수준을 선택합니다.
+
** * 모두 *: 최고 수준의 일관성을 제공합니다. 모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.
** * 강력한 글로벌 *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.
** * 강력한 사이트 *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.
** * Read-After-new-write * (기본값): 새 객체에 대해 읽기-쓰기 후 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.
** * 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.


. 변경 내용 저장 * 을 선택합니다.

