---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 테넌트 그룹을 생성하기 전에 해당 그룹에 할당할 권한을 고려하십시오. 테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다. 사용자는 하나 이상의 그룹에 속할 수 있습니다. 사용자가 여러 그룹에 속한 경우 권한은 누적됩니다. 
---
= 테넌트 관리 권한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 그룹을 생성하기 전에 해당 그룹에 할당할 권한을 고려하십시오. 테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다. 사용자는 하나 이상의 그룹에 속할 수 있습니다. 사용자가 여러 그룹에 속한 경우 권한은 누적됩니다.

테넌트 관리자에 로그인하거나 테넌트 관리 API를 사용하려면 사용자가 하나 이상의 권한이 있는 그룹에 속해야 합니다. 로그인할 수 있는 모든 사용자는 다음 작업을 수행할 수 있습니다.

* 대시보드 보기
* 자신의 암호 변경(로컬 사용자의 경우)


모든 권한에 대해 그룹의 액세스 모드 설정은 사용자가 설정을 변경하고 작업을 수행할 수 있는지 또는 관련 설정과 기능만 볼 수 있는지 여부를 결정합니다.


NOTE: 사용자가 여러 그룹에 속해 있고 모든 그룹이 읽기 전용으로 설정되어 있는 경우 사용자는 선택한 모든 설정 및 기능에 대해 읽기 전용 권한을 갖게 됩니다.

그룹에 다음 권한을 할당할 수 있습니다. S3 테넌트와 Swift 테넌트는 다른 그룹 권한을 가집니다.

[cols="1a,3a"]
|===
| 권한 | 설명 


 a| 
루트 액세스
 a| 
테넌트 관리자 및 테넌트 관리 API에 대한 전체 액세스를 제공합니다.

* 참고: * Swift 사용자는 테넌트 계정에 로그인하려면 루트 액세스 권한이 있어야 합니다.



 a| 
관리자
 a| 
Swift 테넌트만 해당. 이 테넌트 계정에 대한 Swift 컨테이너 및 객체에 대한 전체 액세스를 제공합니다

* 참고: * Swift 사용자는 Swift REST API를 사용하여 모든 작업을 수행하려면 Swift 관리자 권한이 있어야 합니다.



 a| 
자체 S3 자격 증명을 관리합니다
 a| 
사용자가 자신의 S3 액세스 키를 생성하고 제거할 수 있습니다. 이 권한이 없는 사용자는 * storage(S3) * > * My S3 access keys * 메뉴 옵션을 볼 수 없습니다.



 a| 
모든 버킷을 관리합니다
 a| 
* S3 테넌트: 사용자가 테넌트 관리자 및 테넌트 관리 API를 사용하여 S3 버킷을 생성 및 삭제하고 S3 버킷 또는 그룹 정책에 관계없이 테넌트 계정의 모든 S3 버킷을 관리할 수 있습니다.
+
이 권한이 없는 사용자는 * Bucket * 메뉴 옵션이 표시되지 않습니다.

* Swift 테넌트: Swift 사용자가 테넌트 관리 API를 사용하여 Swift 컨테이너의 정합성 수준을 제어할 수 있습니다.


* 참고: * 테넌트 관리 API에서 Swift 그룹에 모든 버킷 관리 권한만 할당할 수 있습니다. 테넌트 관리자를 사용하여 Swift 그룹에 이 권한을 할당할 수 없습니다.



 a| 
엔드포인트 관리
 a| 
사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 플랫폼 서비스 엔드포인트를 생성하거나 편집할 수 있습니다. 이 엔드포인트는 StorageGRID 플랫폼 서비스의 대상으로 사용됩니다.

이 권한이 없는 사용자는 * 플랫폼 서비스 끝점 * 메뉴 옵션이 표시되지 않습니다.



 a| 
S3 콘솔을 통해 오브젝트 관리
 a| 
Manage All Bucket(모든 버킷 관리) 권한과 함께 사용하면 사용자가 Bucket(버킷) 페이지에서 실험 S3 콘솔에 액세스할 수 있습니다. 이 권한이 있지만 모든 버킷 관리 권한이 없는 사용자는 여전히 실험 S3 콘솔로 직접 이동할 수 있습니다.

|===