---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: StorageGRID 시스템을 설치하는 동안 문제가 발생하면 설치 로그 파일에 액세스할 수 있습니다. 
---
= 설치 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템을 설치하는 동안 문제가 발생하면 설치 로그 파일에 액세스할 수 있습니다.

다음은 문제를 해결하기 위해 기술 지원 부서에서 필요로 하는 기본 설치 로그 파일입니다.

* `/var/local/log/install.log` (모든 그리드 노드에 있음)
* `/var/local/log/gdu-server.log` (기본 관리 노드에서 찾을 수 있음)


.관련 정보
로그 파일에 액세스하는 방법은 을 참조하십시오 link:../monitor/logs-files-reference.html["로그 파일 참조"].

추가 도움이 필요한 경우 에 문의하십시오 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^].



== 가상 머신 리소스 예약을 조정해야 합니다

OVF 파일에는 각 그리드 노드가 효율적으로 작동할 수 있는 충분한 RAM 및 CPU를 포함하도록 설계된 리소스 예약이 포함됩니다. VMware에 이러한 OVF 파일을 구축하여 가상 머신을 생성하는 경우 미리 정의된 리소스 수를 사용할 수 없으면 가상 머신이 시작되지 않습니다.

.이 작업에 대해
VM 호스트에 각 그리드 노드에 대한 리소스가 충분하다고 확신하는 경우 각 가상 머신에 할당된 리소스를 수동으로 조정한 다음 가상 머신을 시작합니다.

.단계
. VMware vSphere 하이퍼바이저 클라이언트 트리에서 시작되지 않은 가상 머신을 선택합니다.
. 가상 머신을 마우스 오른쪽 버튼으로 클릭하고 * 설정 편집 * 을 선택합니다.
. 가상 머신 속성 창에서 * 리소스 * 탭을 선택합니다.
. 가상 머신에 할당된 리소스를 조정합니다.
+
.. CPU * 를 선택한 다음 예약 슬라이더를 사용하여 이 가상 머신에 예약된 MHz를 조정합니다.
.. Memory*를 선택한 다음 Reservation 슬라이더를 사용하여 이 가상 머신에 예약된 MB를 조정합니다.


. 확인 * 을 클릭합니다.
. 동일한 VM 호스트에서 호스팅되는 다른 가상 머신에 대해 필요에 따라 이 작업을 반복합니다.

