---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: browser inactivity timeout, inactive users 
summary: 특정 시간 이상 사용하지 않는 경우 Grid Manager 및 Tenant Manager 사용자가 로그아웃되는지 여부를 제어할 수 있습니다. 
---
= 브라우저 비활성 시간 초과 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 시간 이상 사용하지 않는 경우 Grid Manager 및 Tenant Manager 사용자가 로그아웃되는지 여부를 제어할 수 있습니다.

.시작하기 전에
* 를 사용하여 그리드 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].
* 루트 액세스 권한이 있습니다.


.이 작업에 대해
브라우저 비활성 시간 초과 기본값은 15분입니다. 사용자의 브라우저가 이 시간 동안 활성화되어 있지 않으면 사용자가 로그아웃됩니다.

필요에 따라 * 다음 이후 비활성 사용자 로그아웃 * 옵션을 설정하여 제한 시간을 늘리거나 줄일 수 있습니다.

브라우저 비활성 시간 초과는 다음과 같은 방법으로 제어됩니다.

* 시스템 보안을 위해 포함되어 있는 별도의 구성 불가능한 StorageGRID 타이머입니다. 기본적으로 각 사용자의 인증 토큰은 사용자가 로그인 한 후 16시간 후에 만료됩니다. 사용자의 인증이 만료되면 브라우저 비활성 시간 초과가 비활성화되거나 브라우저 시간 초과 값에 도달하지 않은 경우에도 해당 사용자는 자동으로 로그아웃됩니다. 토큰을 갱신하려면 사용자가 다시 로그인해야 합니다.
* StorageGRID에 대해 SSO(Single Sign-On)가 활성화된 경우 ID 공급자에 대한 시간 제한 설정입니다.
+
SSO가 활성화되어 있고 사용자의 브라우저가 시간 초과되면 사용자는 SSO 자격 증명을 다시 입력하여 StorageGRID에 다시 액세스해야 합니다. 을 참조하십시오 link:configuring-sso.html["Single Sign-On 구성"].



.단계
. 구성 * > * 보안 * > * 보안 설정 * 을 선택합니다.
. Browser inactivity timeout *(브라우저 비활성 시간 초과 *) 탭을 선택합니다.
. 다음 이후 * 사용자 로그아웃 * 필드에서 브라우저 시간 제한 기간을 60초에서 7일 사이로 지정합니다.
+
브라우저 제한 시간을 초, 분, 시간 또는 일 단위로 지정할 수 있습니다.

. 저장 * 을 선택합니다. 브라우저가 지정된 시간 동안 비활성 상태인 경우 사용자는 Grid Manager 또는 Tenant Manager에서 로그아웃됩니다.
+
새 설정은 현재 로그인한 사용자에게는 영향을 주지 않습니다. 사용자는 다시 로그인하거나 브라우저를 새로 고쳐야 새 시간 초과 설정을 적용할 수 있습니다.


