---
permalink: admin/kms-viewing-details.html 
sidebar: sidebar 
keywords: view kms, view key management server 
summary: 'StorageGRID 시스템의 각 키 관리 서버 \(KMS\)에 대한 정보(서버 및 클라이언트 인증서의 현재 상태 포함)를 볼 수 있습니다.' 
---
= KMS 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서버 및 클라이언트 인증서의 현재 상태를 포함하여 StorageGRID 시스템의 각 키 관리 서버(KMS)에 대한 정보를 볼 수 있습니다.

.단계
. 구성 * > * 보안 * > * 키 관리 서버 * 를 선택합니다.
+
키 관리 서버 페이지가 나타납니다. 구성 세부 정보 탭에는 구성된 모든 키 관리 서버가 표시됩니다.

. 각 KMS에 대한 표의 정보를 검토합니다.
+
[cols="1a,2a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
KMS 이름
 a| 
KMS의 설명 이름입니다.



 a| 
키 이름
 a| 
KMS에서 StorageGRID 클라이언트의 키 별칭입니다.



 a| 
의 키를 관리합니다
 a| 
KMS와 관련된 StorageGRID 사이트

이 필드에는 특정 StorageGRID 사이트 또는 다른 KMS(기본 KMS)가 관리하지 않는 사이트의 이름이 표시됩니다.*



 a| 
호스트 이름
 a| 
KMS의 정규화된 도메인 이름 또는 IP 주소입니다.

두 개의 키 관리 서버로 구성된 클러스터가 있는 경우 두 서버의 정규화된 도메인 이름 또는 IP 주소가 나열됩니다. 클러스터에 키 관리 서버가 두 개 이상 있는 경우 첫 번째 KMS의 정규화된 도메인 이름 또는 IP 주소가 클러스터에 있는 추가 키 관리 서버의 수와 함께 나열됩니다.

예를 들면 다음과 같습니다. `10.10.10.10 and 10.10.10.11` 또는 `10.10.10.10 and 2 others`.

클러스터의 모든 호스트 이름을 보려면 KMS를 열고 * 편집 * 또는 * 작업 * > * 편집 * 을 선택합니다.



 a| 
인증서 만료
 a| 
서버 인증서, 선택적 CA 인증서 및 클라이언트 인증서의 현재 상태: 유효, 만료, 만료 임박 또는 알 수 없음.

* 참고: * StorageGRID 인증서 만료에 대한 업데이트를 받는 데 30분 정도 걸릴 수 있습니다. 현재 값을 보려면 웹 브라우저를 새로 고쳐야 합니다.

|===
. 인증서 만료일이 알 수 없는 경우 최대 30분 정도 기다린 다음 웹 브라우저를 새로 고칩니다.
+

NOTE: KMS를 추가한 직후 키 관리 서버 페이지의 인증서 만료는 알 수 없음으로 표시됩니다. 각 인증서의 실제 상태를 가져오는 데 30분 정도 StorageGRID 걸릴 수 있습니다. 실제 상태를 보려면 웹 브라우저를 새로 고쳐야 합니다.

. 인증서 만료 열에 인증서가 만료되었거나 만료 시기가 임박했음을 나타내는 경우 가능한 한 빨리 문제를 해결하십시오.
+
KMS CA 인증서 만료 *, * KMS 클라이언트 인증서 만료 * 및 * KMS 서버 인증서 만료 * 알림이 트리거되면 각 경고에 대한 설명을 기록하고 권장 조치를 수행합니다.

+

CAUTION: 데이터 액세스를 유지하려면 가능한 한 빨리 인증서 문제를 해결해야 합니다.

. 이 KMS에 대한 인증서 세부 정보를 보려면 표에서 KMS 이름을 선택합니다.
. KMS 요약 페이지에서 서버 인증서와 클라이언트 인증서 모두에 대한 메타데이터와 인증서 PEM을 검토합니다. 필요에 따라 * 인증서 편집 * 을 선택하여 인증서를 새 인증서로 바꿉니다.

