---
permalink: admin/kms-viewing-encrypted-nodes.html 
sidebar: sidebar 
keywords: view encrypted nodes, kms nodes, appliances with kms 
summary: 노드 암호화 설정이 활성화된 StorageGRID 시스템의 어플라이언스 노드에 대한 정보를 볼 수 있습니다. 
---
= 암호화된 노드를 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 암호화 * 설정이 활성화된 StorageGRID 시스템의 어플라이언스 노드에 대한 정보를 볼 수 있습니다.

.단계
. 구성 * > * 보안 * > * 키 관리 서버 * 를 선택합니다.
+
키 관리 서버 페이지가 나타납니다. 구성 세부 정보 탭에는 구성된 모든 키 관리 서버가 표시됩니다.

. 페이지 상단에서 * 암호화된 노드 * 탭을 선택합니다.
+
암호화된 노드 탭에는 * 노드 암호화 * 설정이 활성화된 StorageGRID 시스템의 어플라이언스 노드가 나열됩니다.

. 각 어플라이언스 노드에 대해 표의 정보를 검토합니다.
+
[cols="1a,2a"]
|===
| 열 | 설명 


 a| 
노드 이름
 a| 
어플라이언스 노드의 이름입니다.



 a| 
노드 유형입니다
 a| 
노드 유형: 스토리지, 관리자 또는 게이트웨이



 a| 
사이트
 a| 
노드가 설치된 StorageGRID 사이트의 이름입니다.



 a| 
KMS 이름
 a| 
노드에 사용된 KMS의 설명 이름입니다.

KMS가 나열되지 않으면 구성 세부 정보 탭을 선택하여 KMS를 추가합니다.

link:kms-adding.html["KMS(키 관리 서버) 추가"]



 a| 
키 UID
 a| 
어플라이언스 노드에서 데이터를 암호화하고 해독하는 데 사용되는 암호화 키의 고유 ID입니다. 전체 키 UID를 보려면 셀 위에 커서를 놓습니다.

대시(--)는 어플라이언스 노드와 KMS 사이의 연결 문제로 인해 키 UID를 알 수 없음을 나타냅니다.



 a| 
상태
 a| 
KMS와 어플라이언스 노드 간의 연결 상태입니다. 노드가 연결되어 있으면 타임스탬프가 30분마다 업데이트됩니다. KMS 구성이 변경된 후 연결 상태를 업데이트하는 데 몇 분 정도 걸릴 수 있습니다.

* 참고: * 새 값을 보려면 웹 브라우저를 새로 고쳐야 합니다.

|===
. 상태 열에 KMS 문제가 표시되면 즉시 문제를 해결하십시오.
+
KMS가 정상적으로 작동하는 동안 KMS*에 연결됨 상태로 표시됩니다. 노드가 그리드에서 연결이 끊어지면 노드 연결 상태가 표시됩니다(관리자 다운 또는 알 수 없음).

+
다른 상태 메시지는 이름이 같은 StorageGRID 알림에 해당합니다.

+
** KMS 구성을 로드하지 못했습니다
** KMS 연결 오류입니다
** KMS 암호화 키 이름을 찾을 수 없습니다
** KMS 암호화 키 회전이 실패했습니다
** 킬로미터 키가 어플라이언스 볼륨을 해독하지 못했습니다
** KMS가 구성되지 않았습니다


+
이러한 경고에 대해 권장되는 작업을 수행합니다.




CAUTION: 데이터를 완벽하게 보호하려면 모든 문제를 즉시 해결해야 합니다.
