---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다. 
---
= 관리 노드란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다.

그리드 관리자 또는 테넌트 관리자에 로그인할 때 관리 노드에 연결됩니다. 모든 관리 노드에 연결할 수 있으며 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다. 그러나 기본 관리 노드를 사용하여 유지 관리 절차를 수행해야 합니다.

관리 노드를 사용하여 S3 및 Swift 클라이언트 트래픽의 로드 밸런싱을 수행할 수도 있습니다.



== 기본 발신자는 무엇입니까

StorageGRID 배포에 여러 개의 관리 노드가 포함된 경우 기본 관리 노드는 경고 알림, AutoSupport 메시지, SNMP 트랩 및 알림, 레거시 경보 알림을 보내는 기본 보낸 사람이 됩니다.

정상적인 시스템 작업에서 기본 설정 보낸 사람만이 알림을 보냅니다. 그러나 다른 모든 관리 노드는 기본 설정 발신자를 모니터링합니다. 문제가 감지되면 다른 관리 노드가 _대기 보낸 사람_ 역할을 합니다.

다음과 같은 경우 여러 알림이 전송될 수 있습니다.

* 관리 노드가 서로 "표시"되는 경우 기본 설정 보낸 사람과 대기 보낸 사람 모두 알림 보내기를 시도하며 여러 개의 알림 복사본이 수신될 수 있습니다.
* 대기 보낸 사람이 기본 설정 보낸 사람과 관련된 문제를 감지하고 알림을 보내기 시작하면 기본 설정 보낸 사람이 알림을 다시 보낼 수 있습니다. 이 경우 중복 알림이 전송될 수 있습니다. 대기 보낸 사람이 더 이상 기본 설정 보낸 사람의 오류를 감지하지 않으면 알림 전송을 중지합니다.
+

NOTE: AutoSupport 메시지를 테스트할 때 모든 관리 노드가 테스트 이메일을 보냅니다. 알림 알림을 테스트할 때는 모든 관리 노드에 로그인하여 연결을 확인해야 합니다.





== 관리 노드에 대한 기본 서비스

다음 표에서는 관리 노드의 기본 서비스를 보여 줍니다. 그러나 이 테이블에는 모든 노드 서비스가 나열되지는 않습니다.

[cols="1a,2a"]
|===
| 서비스 | 키 기능 


 a| 
AMS(감사 관리 시스템)
 a| 
시스템 활동 및 이벤트를 추적합니다.



 a| 
구성 관리 노드(CMN)
 a| 
시스템 전체 구성을 관리합니다. 기본 관리자 노드만.



 a| 
관리 애플리케이션 프로그램 인터페이스(관리 API)
 a| 
Grid Management API 및 Tenant Management API의 요청을 처리합니다.



 a| 
고가용성
 a| 
관리 노드 및 게이트웨이 노드 그룹의 고가용성 가상 IP 주소를 관리합니다.

* 참고: * 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
로드 밸런서
 a| 
클라이언트에서 스토리지 노드로 S3 및 Swift 트래픽의 로드 밸런싱을 제공합니다.

* 참고: * 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
네트워크 관리 시스템(NMS)
 a| 
그리드 관리자를 위한 기능을 제공합니다.



 a| 
프로메테우스
 a| 
모든 노드의 서비스에서 시계열 메트릭을 수집 및 저장합니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영 체제 및 기본 하드웨어를 모니터링합니다.

|===