---
permalink: admin/what-archive-node-is.html 
sidebar: sidebar 
keywords: archive node 
summary: '선택적으로 각 StorageGRID 데이터 센터 사이트를 아카이브 노드와 함께 구축할 수 있습니다. 그러면 TSM(Tivoli Storage Manager)과 같은 타겟 외부 아카이브 스토리지 시스템에 연결할 수 있습니다.' 
---
= 아카이브 노드란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택적으로 각 StorageGRID 데이터 센터 사이트를 아카이브 노드와 함께 구축할 수 있습니다. 그러면 TSM(Tivoli Storage Manager)과 같은 타겟 외부 아카이브 스토리지 시스템에 연결할 수 있습니다.

[CAUTION]
====
아카이브 노드 지원(S3 API를 사용하여 클라우드로 아카이빙하고 TSM 미들웨어를 사용하여 테이프에 아카이빙하는 경우 모두 지원)은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다. 아카이브 노드에서 외부 아카이브 스토리지 시스템으로 오브젝트를 이동한 후 ILM 클라우드 스토리지 풀로 대체되었으며 이는 더 많은 기능을 제공합니다.

참조:

* link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["객체를 클라우드 스토리지 풀로 마이그레이션합니다"]
* link:../ilm/what-cloud-storage-pool-is.html["클라우드 스토리지 풀 사용"]


또한 StorageGRID 11.7 이하의 활성 ILM 정책에서 아카이브 노드를 제거해야 합니다. 아카이브 노드에 저장된 오브젝트 데이터를 제거하면 향후 업그레이드가 간소화됩니다. 을 참조하십시오 link:../ilm/working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 및 ILM 정책 작업"].

====
아카이브 노드는 객체 데이터의 장기 저장을 위해 외부 아카이브 스토리지 시스템을 대상으로 지정할 수 있는 인터페이스를 제공합니다. 또한 아카이브 노드는 이 연결과 StorageGRID 시스템과 대상 외부 아카이브 스토리지 시스템 간의 개체 데이터 전송을 모니터링합니다.

외부 타겟에 대한 접속을 구성한 후 TSM 성능을 최적화하도록 아카이브 노드를 구성하고, TSM 서버가 용량 또는 사용 불가 상태에 근접할 때 아카이브 노드를 오프라인으로 전환하고, 복제 및 검색 설정을 구성할 수 있습니다. 아카이브 노드에 대한 사용자 지정 알람을 설정할 수도 있습니다.

삭제할 수 없지만 정기적으로 액세스하지 않는 오브젝트 데이터는 언제든지 스토리지 노드의 회전식 디스크에서 벗어나 클라우드 또는 테이프와 같은 외부 아카이브 스토리지로 이동할 수 있습니다. 이러한 오브젝트 데이터 아카이빙은 데이터 센터 사이트의 아카이브 노드 구성과 이 아카이브 노드가 콘텐츠 배치 지침을 위한 "대상"으로 선택된 ILM 규칙 구성을 통해 수행됩니다. 아카이브 노드는 아카이빙된 객체 데이터 자체를 관리하지 않으며, 이는 외부 아카이브 디바이스가 수행합니다.


NOTE: 오브젝트 메타데이터는 아카이빙되지 않지만 스토리지 노드에 유지됩니다.



== ARC 서비스의 정의

아카이브 노드의 아카이브(ARC) 서비스는 TSM 미들웨어를 통해 테이프와 같은 외부 아카이브 스토리지에 대한 연결을 구성하는 데 사용할 수 있는 관리 인터페이스를 제공합니다.

이 서비스는 외부 아카이브 스토리지 시스템과 상호 작용하여 니어라인 스토리지에 대한 오브젝트 데이터를 전송하고 클라이언트 애플리케이션이 아카이빙된 객체를 요청할 때 검색을 수행하는 ARC 서비스입니다. 클라이언트 애플리케이션이 아카이빙된 객체를 요청하면 스토리지 노드는 ARC 서비스에서 객체 데이터를 요청합니다. ARC 서비스는 외부 아카이브 스토리지 시스템에 요청을 하여 요청된 개체 데이터를 검색하여 ARC 서비스로 전송합니다. ARC 서비스는 객체 데이터를 확인하고 이를 스토리지 노드로 전달하여 객체를 요청한 클라이언트 애플리케이션으로 반환합니다.

TSM 미들웨어를 통해 테이프로 아카이빙된 오브젝트 데이터에 대한 요청은 검색 효율성을 위해 관리됩니다. 테이프에 순차적으로 저장된 객체가 동일한 순서로 요청되도록 요청을 주문할 수 있습니다. 그런 다음 요청이 스토리지 디바이스에 제출될 때까지 대기합니다. 아카이브 장치에 따라 서로 다른 볼륨에 있는 개체에 대한 여러 요청을 동시에 처리할 수 있습니다.
