---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html 
sidebar: sidebar 
keywords: ilm manage object rules 
summary: '그리드 관리자는 정보 라이프사이클 관리 \(ILM\) 규칙을 생성하여 S3 REST API 클라이언트 애플리케이션에서 StorageGRID 시스템으로 수집된 오브젝트 데이터를 관리합니다. 그런 다음 이러한 규칙을 ILM 정책에 추가하여 시간 경과에 따라 오브젝트 데이터가 저장되는 방법 및 위치를 결정합니다.' 
---
= StorageGRID ILM 규칙이 개체를 관리하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 정보 라이프사이클 관리(ILM) 규칙을 생성하여 S3 REST API 클라이언트 애플리케이션에서 StorageGRID 시스템으로 수집된 오브젝트 데이터를 관리합니다. 그런 다음 이러한 규칙을 ILM 정책에 추가하여 시간 경과에 따라 오브젝트 데이터가 저장되는 방법 및 위치를 결정합니다.

ILM 설정은 개체의 다음 측면을 결정합니다.

* * 지역 *
+
StorageGRID 시스템(스토리지 풀) 또는 클라우드 스토리지 풀 내에서 오브젝트 데이터의 위치입니다.

* * 스토리지 등급 *
+
오브젝트 데이터를 저장하는 데 사용되는 스토리지의 유형(예: 플래시 또는 회전식 디스크)

* * 손실 방지 *
+
복제, 삭제 코딩 또는 두 가지 유형의 복사본을 만들 수와 복사본 유형을 지정합니다.

* * 보존 *
+
오브젝트의 데이터 관리 방식, 저장 위치 및 데이터 손실을 보호하는 방법에 대한 시간이 지나면서 변동합니다.

* * 수집 중 보호 *
+
수집 중에 오브젝트 데이터를 보호하는 데 사용되는 방법: 동기 배치(Ingest 동작에 대한 균형 또는 엄격 옵션 사용) 또는 중간 복사본 만들기(이중 커밋 옵션 사용).



ILM 규칙을 사용하여 개체를 필터링 및 선택할 수 있습니다. S3을 사용하여 수집된 개체의 경우 ILM 규칙을 통해 다음 메타데이터를 기반으로 개체를 필터링할 수 있습니다.

* 테넌트 계정입니다
* 버킷 이름
* 수집 시간
* 키
* 마지막 액세스 시간입니다
+

NOTE: 기본적으로 마지막 액세스 시간에 대한 업데이트는 모든 S3 버킷에 대해 비활성화됩니다. StorageGRID 시스템에 마지막 액세스 시간 옵션을 사용하는 ILM 규칙이 포함된 경우 해당 규칙에 지정된 S3 버킷의 마지막 액세스 시간에 대한 업데이트를 활성화해야 합니다. Put Bucket Last Access Time 요청인 Tenant Manager를 사용합니다(참조) link:../tenant/enabling-or-disabling-last-access-time-updates.html["마지막 액세스 시간 업데이트를 사용하거나 사용하지 않도록 설정합니다"]) 또는 테넌트 관리 API. 마지막 액세스 시간 업데이트를 설정할 때는 특히 작은 오브젝트가 있는 시스템에서 StorageGRID 성능이 저하될 수 있다는 점에 유의하십시오.

* 위치 제약 조건
* 개체 크기
* 사용자 메타데이터
* 개체 태그


.관련 정보
link:../tenant/index.html["테넌트 계정을 사용합니다"]

link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:put-bucket-last-access-time-request.html["버킷 최종 접근 시간"]
