---
permalink: s3/operations-for-multipart-uploads.html 
sidebar: sidebar 
keywords: operations, multipart uploads, uploads, rest API 
summary: 이 섹션에서는 StorageGRID가 멀티파트 업로드 작업을 지원하는 방법에 대해 설명합니다. 
---
= 멀티파트 업로드 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 StorageGRID가 멀티파트 업로드 작업을 지원하는 방법에 대해 설명합니다.

다음 조건 및 참고 사항은 모든 다중 파트 업로드 작업에 적용됩니다.

* 해당 버킷에 대한 다중 파트 업로드 나열 쿼리 결과는 불완전한 결과를 반환할 수 있으므로 단일 버킷에 대한 동시 다중 파트 업로드 1,000개를 초과할 수 없습니다.
* StorageGRID는 여러 파트에 대해 AWS 크기 제한을 적용합니다. S3 클라이언트는 다음 지침을 따라야 합니다.
+
** 멀티파트 업로드의 각 파트는 5MiB(5,242,880바이트)와 5GiB(5,368,709,120바이트) 사이여야 합니다.
** 마지막 부분은 5MiB(5,242,880바이트)보다 작을 수 있습니다.
** 일반적으로 파트 크기는 가능한 한 커야합니다. 예를 들어, 100GiB 개체의 경우 5GiB의 파트 크기를 사용합니다. 각 파트는 고유한 개체로 간주되므로 큰 파트 크기를 사용하면 StorageGRID 메타데이터 오버헤드가 줄어듭니다.
** 5GiB보다 작은 오브젝트의 경우 대신 비다중 파트 업로드를 사용하는 것이 좋습니다.


* ILM 규칙이 Balanced 또는 Strict 수집 동작을 사용하는 경우 ILM은 다중 파트 개체의 각 부분을 인제스트할 때 계산되고 다중 파트 업로드가 완료될 때 전체 개체에 대해 평가됩니다. 이 사항이 개체 및 파트 배치에 미치는 영향에 대해 알고 있어야 합니다.
+
** S3 멀티파트 업로드가 진행 중인 동안 ILM이 변경되면 멀티파트 업로드가 완료될 때 개체의 일부 부분이 현재 ILM 요구 사항을 충족하지 못할 수 있습니다. 올바르게 배치되지 않은 모든 부품은 ILM 재평가를 위해 대기 중이며 나중에 올바른 위치로 이동됩니다.
** 파트에 대한 ILM을 평가할 때 StorageGRID은 개체의 크기가 아닌 파트 크기를 필터링합니다. 즉, 개체의 일부를 개체에 대한 ILM 요구 사항을 전체가 충족하지 않는 위치에 저장할 수 있습니다. 예를 들어, 규칙이 모든 오브젝트 10GB 이상이 DC1에 저장되는 반면 모든 작은 오브젝트는 DC2에 저장되는 것으로 지정하는 경우 10개 부분 멀티파트 업로드의 각 1GB 부분은 DC2에 저장됩니다. 개체에 대한 ILM을 전체적으로 평가할 때 개체의 모든 부분이 DC1로 이동합니다.


* 모든 멀티파트 업로드 작업은 StorageGRID 정합성 제어를 지원합니다.
* 필요한 경우 다중 파트 업로드와 함께 서버측 암호화를 사용할 수 있습니다. SSE(StorageGRID 관리 키 사용 시 서버 측 암호화)를 사용하려면 를 포함합니다 `x-amz-server-side-encryption` 다중 파트 업로드 시작 요청의 요청 헤더만 SSE-C(고객이 제공한 키와 함께 서버측 암호화)를 사용하려면 다중 파트 업로드 시작 요청 및 각 후속 업로드 파트 요청에서 동일한 세 가지 암호화 키 요청 헤더를 지정합니다.


[cols="2a,3a"]
|===
| 작동 | 구축 


 a| 
다중 파트 업로드 나열
 a| 
을 참조하십시오 link:list-multipart-uploads.html["다중 파트 업로드 나열"]



 a| 
멀티파트 업로드를 시작합니다
 a| 
을 참조하십시오 link:initiate-multipart-upload.html["멀티파트 업로드를 시작합니다"]



 a| 
부품 업로드
 a| 
을 참조하십시오 link:upload-part.html["부품 업로드"]



 a| 
업로드 부품 - 복사
 a| 
을 참조하십시오 link:upload-part-copy.html["업로드 부품 - 복사"]



 a| 
멀티파트 업로드를 완료합니다
 a| 
을 참조하십시오 link:complete-multipart-upload.html["멀티파트 업로드를 완료합니다"]



 a| 
멀티파트 업로드를 중단합니다
 a| 
모든 Amazon S3 REST API 동작으로 구현됩니다. 예고 없이 변경될 수 있습니다.



 a| 
파트 목록
 a| 
모든 Amazon S3 REST API 동작으로 구현됩니다. 예고 없이 변경될 수 있습니다.

|===
.관련 정보
* link:consistency-controls.html["일관성 제어"]
* link:using-server-side-encryption.html["서버측 암호화를 사용합니다"]

