---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: S3 POST 오브젝트 복원 요청을 사용하여 클라우드 스토리지 풀에 저장된 오브젝트를 복원할 수 있습니다. 
---
= 사후 개체 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 POST 오브젝트 복원 요청을 사용하여 클라우드 스토리지 풀에 저장된 오브젝트를 복원할 수 있습니다.



== 지원되는 요청 유형입니다

StorageGRID는 개체 복원을 위한 POST 개체 복원 요청만 지원합니다. 는 지원하지 않습니다 `SELECT` 복원 유형. 반품 요청을 선택합니다 `XNotImplemented`.



== 버전 관리

필요에 따라 를 지정합니다 `versionId` 버전 관리되는 버킷에서 특정 버전의 오브젝트 복원 를 지정하지 않은 경우 `versionId`, 개체의 최신 버전이 복원됩니다



== 클라우드 스토리지 풀 객체에 대한 POST 객체 복구의 동작

개체가 클라우드 스토리지 풀에 저장된 경우(정보 수명 주기 관리를 통해 개체 관리 지침 참조) POST 개체 복원 요청은 개체의 상태에 따라 다음과 같은 동작을 수행합니다. 자세한 내용은 " 헤드 개체 "를 참조하십시오.


NOTE: 객체가 클라우드 스토리지 풀에 저장되어 있고 하나 이상의 오브젝트 복제본도 그리드에 있는 경우 POST 객체 복원 요청을 실행하여 객체를 복원할 필요가 없습니다. 대신 Get Object 요청을 사용하여 로컬 복사본을 직접 검색할 수 있습니다.

[cols="1a,2a"]
|===
| 개체의 상태입니다 | POST 개체 복원 동작 


 a| 
StorageGRID로 수집되었지만 ILM에서 아직 평가되지 않은 오브젝트 또는 클라우드 스토리지 풀에 없는 오브젝트
 a| 
`403 Forbidden`, `InvalidObjectState`



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
`200 OK` 변경 사항이 없습니다.

* 참고 *: 개체가 검색할 수 없는 상태로 전환되기 전에는 개체를 변경할 수 없습니다 `expiry-date`.



 a| 
개체가 검색할 수 없는 상태로 전환되었습니다
 a| 
`202 Accepted` 요청 본문에서 지정한 일 수에 대해 검색할 수 있는 객체 복제본을 클라우드 스토리지 풀에 복구합니다. 이 기간이 끝나면 객체는 복구할 수 없는 상태로 돌아갑니다.

필요에 따라 를 사용합니다 `Tier` 복원 작업을 완료하는 데 걸리는 시간을 결정하는 요청 요소입니다 (`Expedited`, `Standard`, 또는 `Bulk`)를 클릭합니다. 를 지정하지 않은 경우 `Tier`, `Standard` 계층이 사용됩니다.

* 중요 *: 오브젝트가 S3 Glacier Deep Archive로 전환된 경우 또는 Cloud Storage Pool에서 Azure Blob 스토리지를 사용하는 경우 를 사용하여 복원할 수 없습니다 `Expedited` 계층. 다음 오류가 반환됩니다 `403 Forbidden`, `InvalidTier`: `Retrieval option is not supported by this storage class`.



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
`409 Conflict`, `RestoreAlreadyInProgress`



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
`200 OK`

* 참고: * 개체가 검색 가능한 상태로 복원되면 이를 변경할 수 있습니다 `expiry-date` 에 대한 새 값을 사용하여 POST 개체 복원 요청을 다시 발행합니다 `Days`. 복원 날짜는 요청 시간을 기준으로 업데이트됩니다.

|===
.관련 정보
link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]

link:head-object.html["헤드 개체"]

link:s3-operations-tracked-in-audit-logs.html["S3 작업이 감사 로그에서 추적되었습니다"]
