---
permalink: monitor/configure-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, configure syslog server, configure external syslog server. log destinations 
summary: 모든 StorageGRID 노드는 감사 메시지를 생성하여 시스템 활동 및 이벤트를 추적합니다. 감사 수준을 조정하여 기록된 감사 메시지의 유형과 수를 늘리거나 줄일 수 있습니다. 
---
= 감사 메시지 및 로그 대상을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 메시지와 로그는 시스템 활동 및 보안 이벤트를 기록하고, 모니터링 및 문제 해결에 필수적인 도구입니다. 감사 수준을 조정하여 기록된 감사 메시지의 유형과 수를 늘리거나 줄일 수 있습니다. 선택적으로 감사 메시지를 읽고 쓸 클라이언트에 포함할 HTTP 요청 헤더를 정의할 수 있습니다. 외부 syslog 서버를 구성하고 감사 정보의 대상을 변경할 수도 있습니다.

감사 메시지에 대한 자세한 내용은 을 참조하십시오 link:../audit/index.html["감사 로그를 검토합니다"].

.시작하기 전에
* 를 사용하여 그리드 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].
* 유지 관리 또는 루트 액세스 권한이 있습니다.


.이 작업에 대해
모든 StorageGRID 노드는 감사 메시지와 로그를 생성하여 시스템 활동 및 이벤트를 추적합니다. 기본적으로 감사 정보는 관리 노드의 감사 로그로 전송됩니다. 감사 레벨을 조정하여 감사 로그에 기록되는 감사 메시지의 유형과 수를 늘리거나 줄일 수 있습니다. 선택적으로 수동 수집을 위해 원래 노드에 임시로 저장되는 감사 정보를 구성할 수 있습니다.


IMPORTANT: 대규모 그리드가 있거나, 여러 유형의 S3 애플리케이션을 사용하거나, 모든 감사 데이터를 보존하려는 경우, 외부 syslog 서버를 구성하고 감사 정보를 원격으로 저장합니다. 외부 서버를 사용하면 감사 데이터의 완성도를 낮추지 않고도 감사 메시지 로깅의 성능 영향을 최소화할 수 있습니다. 을 참조하십시오 link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버에 대한 고려 사항"] 를 참조하십시오.



== 감사 로그에서 감사 메시지 수준을 변경합니다

감사 로그에서 다음 메시지 범주에 대해 서로 다른 감사 수준을 설정할 수 있습니다.

[cols="1a,3a"]
|===
| 감사 범주 | 설명 


 a| 
시스템
 a| 
기본적으로 이 수준은 보통 으로 설정됩니다. 을 참조하십시오 link:../audit/system-audit-messages.html["시스템 감사 메시지"].



 a| 
스토리지
 a| 
기본적으로 이 수준은 오류 로 설정됩니다. 을 참조하십시오 link:../audit/object-storage-audit-messages.html["오브젝트 스토리지 감사 메시지"].



 a| 
관리
 a| 
기본적으로 이 수준은 보통 으로 설정됩니다. 을 참조하십시오 link:../audit/management-audit-message.html["관리 감사 메시지입니다"].



 a| 
클라이언트 읽기
 a| 
기본적으로 이 수준은 보통 으로 설정됩니다. 을 참조하십시오 link:../audit/client-read-audit-messages.html["클라이언트가 감사 메시지를 읽습니다"].



 a| 
클라이언트 쓰기
 a| 
기본적으로 이 수준은 보통 으로 설정됩니다. 을 참조하십시오 link:../audit/client-write-audit-messages.html["클라이언트가 감사 메시지를 기록합니다"].



 a| 
ILM 작업
 a| 
기본적으로 이 수준은 보통 으로 설정됩니다. 을 참조하십시오 link:../audit/ilm-audit-messages.html["ILM 운영 감사 메시지"].

|===

NOTE: 이 기본값은 버전 10.3 이상을 사용하여 StorageGRID를 처음 설치한 경우에 적용됩니다. 이전 버전의 StorageGRID에서 업그레이드한 경우 모든 범주의 기본값은 보통으로 설정됩니다.


NOTE: 업그레이드 중에는 감사 수준 구성이 즉시 적용되지 않습니다.

.단계
. 구성 * > * 모니터링 * > * 감사 및 syslog 서버 * 를 선택합니다.
. 각 감사 메시지 범주에 대해 드롭다운 목록에서 감사 수준을 선택합니다.
+
[cols="1a,3a"]
|===
| 감사 수준 | 설명 


 a| 
꺼짐
 a| 
범주의 감사 메시지가 기록되지 않습니다.



 a| 
오류
 a| 
오류 메시지만 기록됩니다. 결과 코드가 "성공"하지 않은 감사 메시지입니다(SUCS).



 a| 
정상
 a| 
표준 트랜잭션 메시지가 기록됩니다. -- 범주에 대한 이 지침에 나열된 메시지입니다.



 a| 
디버그
 a| 
사용되지 않음. 이 수준은 일반 감사 수준과 동일하게 작동합니다.

|===
+
특정 수준에 포함되는 메시지에는 더 높은 수준으로 기록되는 메시지가 포함됩니다. 예를 들어 일반 수준에는 모든 오류 메시지가 포함됩니다.

+

NOTE: S3 응용 프로그램에 대한 클라이언트 읽기 작업에 대한 자세한 레코드가 필요하지 않은 경우 * 클라이언트 읽기 * 설정을 * 오류 * 로 변경하여 감사 로그에 기록되는 감사 메시지 수를 줄입니다.

. 선택적으로 * 감사 프로토콜 헤더 * 에서 클라이언트 읽기 및 쓰기 감사 메시지에 포함할 HTTP 요청 헤더를 정의합니다. 0개 이상의 문자를 일치시키려면 별표(\ *)를 와일드카드로 사용하십시오. 이스케이프 시퀀스(\ *)를 사용하여 리터럴 별표를 일치시킵니다.
+

NOTE: 감사 프로토콜 헤더는 S3 및 Swift 요청에만 적용됩니다.

. 필요한 경우 추가 헤더를 만들려면 * 다른 헤더 추가 * 를 선택합니다.
+
HTTP 헤더가 요청에서 검색되면 HTRH 필드 아래의 감사 메시지에 포함됩니다.

+

NOTE: 감사 프로토콜 요청 헤더는 * 클라이언트 읽기 * 또는 * 클라이언트 쓰기 * 에 대한 감사 수준이 * 꺼짐 * 이 아닌 경우에만 기록됩니다.

. 저장 * 을 선택합니다
+
구성이 성공적으로 저장되었음을 나타내는 녹색 배너가 표시됩니다.





== 외부 syslog 서버를 사용합니다

감사 정보를 원격으로 저장하려면 외부 syslog 서버를 구성할 수 있습니다.

* 감사 정보를 외부 syslog 서버에 저장하려면 로 이동합니다 link:../monitor/configuring-syslog-server.html["외부 syslog 서버를 구성합니다"].
* 외부 syslog 서버를 사용하지 않는 경우 로 이동합니다 <<Select-audit-information-destinations,감사 정보 대상을 선택합니다>>.




== 감사 정보 대상을 선택합니다

감사 로그, 보안 이벤트 로그 및 응용 프로그램 로그를 보낼 위치를 지정할 수 있습니다.


NOTE: 일부 대상은 외부 syslog 서버를 사용하는 경우에만 사용할 수 있습니다. 을 참조하십시오 link:../monitor/configuring-syslog-server.html["외부 syslog 서버를 구성합니다"] 외부 syslog 서버를 구성하려면 다음을 수행합니다.


NOTE: StorageGRID 소프트웨어 로그에 대한 자세한 내용은 을 참조하십시오 link:../monitor/storagegrid-software-logs.html#["StorageGRID 소프트웨어 로그"].

. 감사 및 syslog 서버 페이지의 나열된 옵션 중에서 감사 정보의 대상을 선택합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
기본값(관리자 노드/로컬 노드)
 a| 
감사 메시지는 감사 로그에 전송됩니다 (`audit.log`) 및 보안 이벤트 로그 및 애플리케이션 로그는 관리 노드에 저장되며, 이를 생성된 노드("로컬 노드"라고도 함)에 저장됩니다.



 a| 
외부 syslog 서버
 a| 
감사 정보는 외부 syslog 서버로 전송되고 로컬 노드에 저장됩니다. 전송되는 정보의 유형은 외부 syslog 서버를 구성한 방식에 따라 다릅니다. 이 옵션은 외부 syslog 서버를 구성한 후에만 활성화됩니다.



 a| 
관리 노드 및 외부 syslog 서버
 a| 
감사 메시지는 감사 로그에 전송됩니다 (`audit.log`)를 선택하면 감사 정보가 외부 syslog 서버로 전송되고 로컬 노드에 저장됩니다. 전송되는 정보의 유형은 외부 syslog 서버를 구성한 방식에 따라 다릅니다. 이 옵션은 외부 syslog 서버를 구성한 후에만 활성화됩니다.



 a| 
로컬 노드만 해당
 a| 
관리자 노드 또는 원격 syslog 서버로 감사 정보가 전송되지 않습니다. 감사 정보는 감사 정보를 생성한 노드에만 저장됩니다.

* 참고 *: StorageGRID는 공간을 확보하기 위해 주기적으로 이러한 로컬 로그를 제거합니다. 노드의 로그 파일이 1GB에 도달하면 기존 파일이 저장되고 새 로그 파일이 시작됩니다. 로그의 회전 제한은 21개 파일입니다. 22버전의 로그 파일이 만들어지면 가장 오래된 로그 파일이 삭제됩니다. 평균적으로 약 20GB의 로그 데이터가 각 노드에 저장됩니다.

|===
+

NOTE: 모든 로컬 노드에서 생성된 감사 정보는 에 저장됩니다 `/var/local/log/localaudit.log`

. 저장 * 을 선택합니다.
+
경고 메시지가 나타납니다.

. 감사 정보의 대상을 변경하려면 * OK * 를 선택합니다.
+
감사 구성이 저장되었음을 알리는 녹색 배너가 나타납니다.

+
새 로그가 선택한 대상으로 전송됩니다. 기존 로그는 현재 위치에 남아 있습니다.



.관련 정보
link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버에 대한 고려 사항"]

link:../admin/index.html["StorageGRID 관리"]

link:../troubleshoot/troubleshooting-syslog-server.html["외부 syslog 서버의 문제를 해결합니다"]
