---
permalink: monitor/configuring-syslog-server.html 
sidebar: sidebar 
keywords: audit messages, syslog server, configure external syslog server 
summary: 감사 로그, 응용 프로그램 로그 및 보안 이벤트 로그를 그리드 외부의 위치에 저장하려면 다음 절차를 사용하여 외부 syslog 서버를 구성합니다. 
---
= 외부 syslog 서버를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그, 응용 프로그램 로그 및 보안 이벤트 로그를 그리드 외부의 위치에 저장하려면 다음 절차를 사용하여 외부 syslog 서버를 구성합니다.

.시작하기 전에
* 를 사용하여 그리드 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].
* 유지 관리 또는 루트 액세스 권한이 있습니다.
* 로그 파일을 수신하고 저장할 용량이 있는 syslog 서버가 있습니다. 자세한 내용은 을 참조하십시오 link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버에 대한 고려 사항"].
* TLS 또는 RELP/TLS를 사용하려는 경우 올바른 서버 및 클라이언트 인증을 보유하고 있습니다.


.이 작업에 대해
외부 syslog 서버로 감사 정보를 보내려면 먼저 외부 서버를 구성해야 합니다.

감사 정보를 외부 syslog 서버로 전송하면 다음을 수행할 수 있습니다.

* 감사 메시지, 응용 프로그램 로그 및 보안 이벤트와 같은 감사 정보를 보다 효율적으로 수집 및 관리합니다
* 관리 노드를 거치지 않고도 감사 정보가 다양한 스토리지 노드에서 외부 syslog 서버로 직접 전송되므로 관리 노드의 네트워크 트래픽을 줄일 수 있습니다
+

CAUTION: 외부 syslog 서버로 로그를 전송할 때 메시지 끝에서 8192바이트보다 큰 단일 로그가 잘려서 외부 syslog 서버 구현의 일반적인 제한 사항을 따릅니다.

+

NOTE: 외부 syslog 서버에 장애가 발생할 경우 전체 데이터 복구 옵션을 최대화하려면 각 노드에서 최대 20GB의 감사 레코드 로컬 로그(localaudit.log)가 유지됩니다.

+

NOTE: 이 절차에서 사용할 수 있는 구성 옵션이 요구 사항을 충족할 만큼 유연하지 않은 경우 전용 API를 사용하여 추가 구성 옵션을 적용할 수 있습니다 `audit-destinations` 엔드포인트, 예를 들어, 서로 다른 노드 그룹에 서로 다른 syslog 서버를 사용할 수 있습니다.





== 외부 서버를 구성합니다



=== 마법사에 액세스합니다

시작하려면 외부 syslog 서버 구성 마법사에 액세스합니다.

.단계
. 구성 * > * 모니터링 * > * 감사 및 syslog 서버 * 를 선택합니다.
. 감사 및 syslog 서버 페이지에서 * 외부 syslog 서버 구성 * 을 선택합니다. 이전에 외부 syslog 서버를 구성한 경우 * 외부 syslog 서버 편집 * 을 선택합니다.
+
외부 syslog 서버 구성 마법사가 나타납니다.





=== syslog 정보를 입력합니다

외부 syslog 서버에 액세스하는 데 필요한 정보를 StorageGRID에 제공해야 합니다.

.단계
. 마법사의 * syslog 정보 입력 * 단계에 대해 유효한 정규화된 도메인 이름 또는 외부 syslog 서버에 대한 IPv4 또는 IPv6 주소를 * Host * 필드에 입력합니다.
. 외부 syslog 서버의 대상 포트를 입력합니다(1과 65535 사이의 정수여야 함). 기본 포트는 514입니다.
. 외부 syslog 서버로 감사 정보를 보내는 데 사용되는 프로토콜을 선택합니다.
+
TLS * 또는 * RELP/TLS * 를 사용하는 것이 좋습니다. 이러한 옵션 중 하나를 사용하려면 서버 인증서를 업로드해야 합니다. 인증서를 사용하면 그리드와 외부 syslog 서버 간의 연결을 보호할 수 있습니다. 자세한 내용은 을 참조하십시오 link:../admin/using-storagegrid-security-certificates.html["보안 인증서를 관리합니다"].

+
모든 프로토콜 옵션에는 외부 syslog 서버에 대한 지원 및 구성이 필요합니다. 외부 syslog 서버와 호환되는 옵션을 선택해야 합니다.

+

NOTE: 신뢰할 수 있는 이벤트 로깅 프로토콜(RELP)은 syslog 프로토콜의 기능을 확장하여 이벤트 메시지를 안정적으로 제공합니다. RELP를 사용하면 외부 syslog 서버를 다시 시작해야 하는 경우 감사 정보의 손실을 방지할 수 있습니다.

. Continue * 를 선택합니다.
. [[attach-certificate]] * TLS * 또는 * RELP/TLS * 를 선택한 경우 다음 인증서를 업로드하십시오.
+
** * 서버 CA 인증서 *: 외부 syslog 서버를 확인하기 위한 하나 이상의 트러스트된 CA 인증서(PEM 인코딩). 이 인수를 생략하면 기본 Grid CA 인증서가 사용됩니다. 여기에 업로드하는 파일은 CA 번들이 될 수 있습니다.
** * 클라이언트 인증서 *: 외부 syslog 서버(PEM 인코딩)에 대한 인증을 위한 클라이언트 인증서입니다.
** * 클라이언트 개인 키 *: 클라이언트 인증서에 대한 개인 키(PEM 인코딩).
+

NOTE: 클라이언트 인증서를 사용하는 경우 클라이언트 개인 키도 사용해야 합니다. 암호화된 개인 키를 제공하는 경우 암호문도 제공해야 합니다. 키와 암호를 저장해야 하므로 암호화된 개인 키를 사용하면 보안 상의 큰 이점이 없습니다. 사용 가능한 경우 암호화되지 않은 개인 키를 사용하는 것이 좋습니다.

+
... 사용할 인증서 또는 키를 * 찾아보기 * 를 선택합니다.
... 인증서 파일 또는 키 파일을 선택합니다.
... 파일을 업로드하려면 * 열기 * 를 선택합니다.
+
인증서 또는 키 파일 이름 옆에 녹색 확인 표시가 나타나 성공적으로 업로드되었음을 알려줍니다.





. Continue * 를 선택합니다.




=== syslog 콘텐츠를 관리합니다

외부 syslog 서버로 보낼 정보를 선택할 수 있습니다.

.단계
. 마법사의 * syslog 콘텐츠 관리 * 단계에서 외부 syslog 서버로 보낼 감사 정보의 각 유형을 선택합니다.
+
** * 감사 로그 전송 *: StorageGRID 이벤트 및 시스템 활동을 전송합니다
** * 보안 이벤트 전송 *: 권한이 없는 사용자가 로그인을 시도하거나 사용자가 루트로 로그인하는 등의 보안 이벤트를 전송합니다
** * 응용 프로그램 로그 전송 *: 다음과 같은 문제 해결에 유용한 로그 파일을 전송합니다.
+
*** `bycast-err.log`
*** `bycast.log`
*** `jaeger.log`
*** `nms.log` (관리 노드만)
*** `prometheus.log`
*** `raft.log`
*** `hagroups.log`




. 드롭다운 메뉴를 사용하여 보내려는 감사 정보 범주에 대한 심각도 및 기능(메시지 유형)을 선택합니다.
+
심각도 및 설비에 대해 * 통과 * 를 선택하면 원격 syslog 서버로 전송되는 정보는 노드에 로컬로 로그온할 때와 동일한 심각도와 기능을 받습니다. 시설 및 심각도를 설정하면 더욱 쉽게 분석할 수 있도록 로그를 사용자 지정 가능한 방식으로 집계하는 데 도움이 됩니다.

+

NOTE: StorageGRID 소프트웨어 로그에 대한 자세한 내용은 을 참조하십시오 link:../monitor/storagegrid-software-logs.html["StorageGRID 소프트웨어 로그"].

+
.. 심각도 * 의 경우 * 통과 * 를 선택하여 외부 syslog에 전송되는 각 메시지의 심각도 값이 로컬 syslog와 동일하게 되도록 합니다.
+
감사 로그의 경우 * 통과 * 를 선택하면 '정보'가 심각합니다.

+
보안 이벤트의 경우 * 통과 * 를 선택하면 노드의 Linux 배포에서 심각도 값이 생성됩니다.

+
응용 프로그램 로그의 경우 * 통과 * 를 선택하면 문제의 내용에 따라 심각도가 '정보'와 '알림'에 따라 다릅니다. 예를 들어 NTP 서버를 추가하고 HA 그룹을 구성하면 '정보' 값이 제공되지만 SSM 또는 RSM 서비스를 의도적으로 중지하는 경우 '알림'이 표시됩니다.

.. 통과 연결 값을 사용하지 않으려면 0에서 7 사이의 심각도 값을 선택합니다.
+
선택한 값은 이 유형의 모든 메시지에 적용됩니다. 심각도가 고정 값으로 재정의되면 서로 다른 심각도에 대한 정보가 손실됩니다.

+
[cols="1a,3a"]
|===
| 심각도입니다 | 설명 


 a| 
0
 a| 
비상: 시스템을 사용할 수 없습니다



 a| 
1
 a| 
경고: 즉시 조치를 취해야 합니다



 a| 
2
 a| 
심각: 심각 상태



 a| 
3
 a| 
오류: 오류 조건



 a| 
4
 a| 
경고: 경고 조건



 a| 
5
 a| 
주의사항: 정상이지만 중대한 조건



 a| 
6
 a| 
정보: 정보 메시지



 a| 
7
 a| 
디버그: 디버그 레벨 메시지

|===
.. Facility * 의 경우 * PassThrough * 를 선택하여 외부 syslog로 전송되는 각 메시지가 로컬 syslog와 동일한 설비 값을 가지도록 합니다.
+
감사 로그의 경우 * PassThrough * 를 선택하면 외부 syslog 서버로 전송되는 기능이 'local7'입니다.

+
보안 이벤트의 경우 * PassThrough * 를 선택하면 시설 값이 노드의 Linux 배포판에 의해 생성됩니다.

+
응용 프로그램 로그의 경우 * 통과 * 를 선택하면 외부 syslog 서버로 전송된 응용 프로그램 로그의 항목 값은 다음과 같습니다.

+
[cols="1a,2a"]
|===
| 응용 프로그램 로그 | 통과 연결 값입니다 


 a| 
bycast.log
 a| 
사용자 또는 데몬



 a| 
bycast-err.log
 a| 
사용자, 데몬, local3 또는 local4



 a| 
jaeger.log
 a| 
로컬2



 a| 
nms.log
 a| 
로컬3



 a| 
prometheus.log
 a| 
로컬4



 a| 
raft.log
 a| 
로컬5



 a| 
hagroups.log
 a| 
로컬6

|===
.. 통과 연결 값을 사용하지 않으려면 0에서 23 사이의 설비 값을 선택합니다.
+
선택한 값은 이 유형의 모든 메시지에 적용됩니다. 고정 값으로 시설을 재정의하면 다른 시설에 대한 정보가 손실됩니다.

+
[cols="1a,3a"]
|===
| 있습니다 | 설명 


 a| 
0
 a| 
Kern(커널 메시지)



 a| 
1
 a| 
사용자(사용자 수준 메시지)



 a| 
2
 a| 
메일



 a| 
3
 a| 
데몬(시스템 데몬)



 a| 
4
 a| 
인증(보안/인증 메시지)



 a| 
5
 a| 
syslog(syslogd에 의해 내부적으로 생성된 메시지)



 a| 
6
 a| 
LPR(라인 프린터 하위 시스템)



 a| 
7
 a| 
뉴스(네트워크 뉴스 서브시스템)



 a| 
8
 a| 
UUCP



 a| 
9
 a| 
cron(클록 데몬)



 a| 
10
 a| 
보안(보안/인증 메시지)



 a| 
11
 a| 
FTP



 a| 
12
 a| 
NTP



 a| 
13
 a| 
Logaudit(로그 감사)



 a| 
14
 a| 
Logalert(로그 경고)



 a| 
15
 a| 
클록(클록 데몬)



 a| 
16
 a| 
로컬0



 a| 
17
 a| 
로컬1



 a| 
18
 a| 
로컬2



 a| 
19
 a| 
로컬3



 a| 
20
 a| 
로컬4



 a| 
21
 a| 
로컬5



 a| 
22
 a| 
로컬6



 a| 
23
 a| 
로컬7

|===


. Continue * 를 선택합니다.




=== 테스트 메시지를 보냅니다

외부 syslog 서버를 사용하기 전에 그리드의 모든 노드가 외부 syslog 서버로 테스트 메시지를 보내도록 요청해야 합니다. 외부 syslog 서버로 데이터를 전송하기 전에 이러한 테스트 메시지를 사용하여 전체 로그 수집 인프라의 유효성을 확인해야 합니다.


CAUTION: 외부 syslog 서버가 그리드의 각 노드로부터 테스트 메시지를 수신하고 메시지가 예상대로 처리되었음을 확인하기 전까지는 외부 syslog 서버 구성을 사용하지 마십시오.

.단계
. 외부 syslog 서버가 제대로 구성되어 있고 그리드의 모든 노드에서 감사 정보를 수신할 수 있으므로 테스트 메시지를 전송하지 않으려면 * Skip and finish * 를 선택합니다.
+
구성이 성공적으로 저장되었음을 나타내는 녹색 배너가 나타납니다.

. 그렇지 않으면 * 테스트 메시지 전송 * (권장)을 선택합니다.
+
테스트를 중지할 때까지 테스트 결과가 페이지에 계속 표시됩니다. 테스트가 진행되는 동안 감사 메시지는 이전에 구성된 대상으로 계속 전송됩니다.

. 오류가 발생하면 오류를 수정하고 * 테스트 메시지 보내기 * 를 다시 선택합니다.
+
을 참조하십시오 link:../troubleshoot/troubleshooting-syslog-server.html["외부 syslog 서버 문제 해결"] 오류를 해결하는 데 도움이 됩니다.

. 모든 노드가 테스트를 통과했음을 나타내는 녹색 배너가 나타날 때까지 기다립니다.
. syslog 서버를 확인하여 테스트 메시지가 예상대로 수신 및 처리되는지 확인합니다.
+

IMPORTANT: UDP를 사용하는 경우 전체 로그 수집 인프라를 확인합니다. UDP 프로토콜은 다른 프로토콜처럼 엄격한 오류 감지를 허용하지 않습니다.

. Stop and finish * 를 선택합니다.
+
감사 및 syslog 서버 * 페이지로 돌아갑니다. syslog 서버 구성이 성공적으로 저장되었음을 알리는 녹색 배너가 나타납니다.

+

NOTE: 외부 syslog 서버를 포함하는 대상을 선택할 때까지 StorageGRID 감사 정보가 외부 syslog 서버로 전송되지 않습니다.





== 감사 정보 대상을 선택합니다

보안 이벤트 로그, 응용 프로그램 로그 및 감사 메시지 로그를 보낼 위치를 지정할 수 있습니다.


NOTE: StorageGRID 소프트웨어 로그에 대한 자세한 내용은 을 참조하십시오 link:../monitor/storagegrid-software-logs.html["StorageGRID 소프트웨어 로그"].

.단계
. 감사 및 syslog 서버 페이지의 나열된 옵션 중에서 감사 정보의 대상을 선택합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
기본값(관리자 노드/로컬 노드)
 a| 
감사 메시지는 감사 로그에 전송됩니다 (`audit.log`) 및 보안 이벤트 로그 및 애플리케이션 로그는 관리 노드에 저장되며, 이를 생성된 노드("로컬 노드"라고도 함)에 저장됩니다.



 a| 
외부 syslog 서버
 a| 
감사 정보는 외부 syslog 서버로 전송되고 로컬 노드에 저장됩니다. 전송되는 정보의 유형은 외부 syslog 서버를 구성한 방식에 따라 다릅니다. 이 옵션은 외부 syslog 서버를 구성한 후에만 활성화됩니다.



 a| 
관리 노드 및 외부 syslog 서버
 a| 
감사 메시지는 감사 로그에 전송됩니다 (`audit.log`)를 선택하면 감사 정보가 외부 syslog 서버로 전송되고 로컬 노드에 저장됩니다. 전송되는 정보의 유형은 외부 syslog 서버를 구성한 방식에 따라 다릅니다. 이 옵션은 외부 syslog 서버를 구성한 후에만 활성화됩니다.



 a| 
로컬 노드만 해당
 a| 
관리자 노드 또는 원격 syslog 서버로 감사 정보가 전송되지 않습니다. 감사 정보는 감사 정보를 생성한 노드에만 저장됩니다.

* 참고 *: StorageGRID는 공간을 확보하기 위해 주기적으로 이러한 로컬 로그를 제거합니다. 노드의 로그 파일이 1GB에 도달하면 기존 파일이 저장되고 새 로그 파일이 시작됩니다. 로그의 회전 제한은 21개 파일입니다. 22버전의 로그 파일이 만들어지면 가장 오래된 로그 파일이 삭제됩니다. 평균적으로 약 20GB의 로그 데이터가 각 노드에 저장됩니다.

|===
+

NOTE: 모든 로컬 노드에서 생성된 감사 정보는 에 저장됩니다 `/var/local/log/localaudit.log`

. 저장 * 을 선택합니다. 그런 다음 * OK * 를 선택하여 로그 대상에 대한 변경 사항을 적용합니다.
. 외부 syslog 서버 * 또는 * 관리 노드 및 외부 syslog 서버 * 를 감사 정보 대상으로 선택한 경우 추가 경고가 나타납니다. 경고 텍스트를 검토합니다.
+

IMPORTANT: 외부 syslog 서버가 테스트 StorageGRID 메시지를 수신할 수 있는지 확인해야 합니다.

. 감사 정보의 대상을 변경하려면 * OK * 를 선택합니다.
+
감사 구성이 성공적으로 저장되었음을 알리는 녹색 배너가 나타납니다.

+
새 로그가 선택한 대상으로 전송됩니다. 기존 로그는 현재 위치에 남아 있습니다.



.관련 정보
link:../audit/index.html["감사 메시지 개요"]

link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상을 구성합니다"]

link:../audit/system-audit-messages.html["시스템 감사 메시지"]

link:../audit/object-storage-audit-messages.html["오브젝트 스토리지 감사 메시지"]

link:../audit/management-audit-message.html["관리 감사 메시지입니다"]

link:../audit/client-read-audit-messages.html["클라이언트가 감사 메시지를 읽습니다"]

link:../admin/index.html["StorageGRID 관리"]
