---
permalink: maintain/considerations-for-decommissioning-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: 이 절차를 시작하여 하나 이상의 노드를 폐기하기 전에 각 노드 유형을 제거할 때의 영향을 이해해야 합니다. 노드가 성공적으로 해제되면 해당 서비스가 비활성화되고 노드가 자동으로 종료됩니다. 
---
= 그리드 노드 해제에 대한 일반 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차를 시작하여 하나 이상의 노드를 폐기하기 전에 각 노드 유형을 제거할 때의 영향을 이해해야 합니다. 노드가 성공적으로 해제되면 해당 서비스가 비활성화되고 노드가 자동으로 종료됩니다.

노드를 사용 중단할 수 없는 경우 StorageGRID가 잘못된 상태로 유지됩니다. 다음 규칙이 적용됩니다.

* 기본 관리 노드를 해제할 수 없습니다.
* 아카이브 노드의 서비스를 해제할 수 없습니다.
* 네트워크 인터페이스 중 하나가 고가용성(HA) 그룹에 속한 경우에는 관리 노드 또는 게이트웨이 노드를 해제할 수 없습니다.
* 스토리지 노드를 제거하면 ADC 쿼럼에 영향을 줄 수 있습니다.
* 활성 ILM 정책에 필요한 스토리지 노드는 서비스 해제할 수 없습니다.
* 단일 서비스 해제 노드 절차에서 10개 이상의 스토리지 노드를 서비스 해제할 수 없습니다.
* 그리드에 연결이 끊긴 노드(상태가 알 수 없거나 관리상 중단된 노드)가 포함된 경우 연결된 노드를 해제할 수 없습니다. 먼저 연결이 끊긴 노드를 서비스 해제하거나 복구해야 합니다.
* 그리드에 연결이 끊어진 노드가 여러 개 포함된 경우, 소프트웨어를 동시에 모두 해제해야 예기치 않은 결과가 발생할 가능성이 높아집니다.
* 연결이 끊긴 노드를 제거할 수 없는 경우(예: ADC 쿼럼에 필요한 스토리지 노드) 연결이 끊긴 다른 노드는 제거할 수 없습니다.
* 이전 제품을 새 제품으로 교체하려면 다음을 고려하십시오 link:../commonhardware/how-appliance-node-cloning-works.html["어플라이언스 노드 클론 생성"] 확장을 위해 기존 노드를 폐기하거나 새 노드를 추가하는 대신



IMPORTANT: 서비스 해제 절차에서 지시할 때까지 그리드 노드의 가상 머신 또는 기타 리소스를 제거하지 마십시오.
