---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: 스토리지 노드를 폐기하려는 경우 StorageGRID이 해당 노드에서 오브젝트 데이터 및 메타데이터를 관리하는 방법을 이해해야 합니다. 
---
= 스토리지 노드 파기 관련 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 폐기하려는 경우 StorageGRID이 해당 노드에서 오브젝트 데이터 및 메타데이터를 관리하는 방법을 이해해야 합니다.

스토리지 노드를 사용 중단할 때는 다음과 같은 고려 사항 및 제한 사항이 적용됩니다.

* 시스템은 항상 ADC 쿼럼과 활성 ILM 정책을 포함하여 운영 요구 사항을 충족할 수 있는 충분한 스토리지 노드를 포함해야 합니다. 이러한 제한을 충족하려면 기존 스토리지 노드를 폐기하기 전에 확장 작업에서 새 스토리지 노드를 추가해야 할 수 있습니다.
* 스토리지 노드를 서비스 해제할 때 스토리지 노드의 연결이 끊어지면 시스템은 연결된 스토리지 노드의 데이터를 사용하여 데이터를 재구성해야 합니다. 이렇게 하면 데이터가 손실될 수 있습니다.
* 스토리지 노드를 제거할 때 대량의 객체 데이터를 네트워크를 통해 전송해야 합니다. 이러한 전송은 정상적인 시스템 작동에 영향을 주지 않지만 StorageGRID 시스템에서 사용하는 총 네트워크 대역폭에 영향을 줄 수 있습니다.
* 스토리지 노드 사용 중단과 관련된 작업은 일반 시스템 작업과 관련된 작업보다 우선 순위가 낮습니다. 즉, 서비스 해제는 정상적인 StorageGRID 시스템 작동을 방해하지 않으며 시스템 비활성 기간 동안 예약할 필요가 없습니다. 디커미셔닝 작업은 백그라운드에서 수행되므로 프로세스가 완료되는 데 걸리는 시간을 추정하기가 어렵습니다. 일반적으로 시스템이 정숙하거나 한 번에 하나의 스토리지 노드만 제거하는 경우 서비스 해제가 더 빠르게 완료됩니다.
* 스토리지 노드의 서비스를 해제하는 데 며칠 또는 몇 주가 걸릴 수 있습니다. 이에 따라 이 절차를 계획하십시오. 서비스 해제 프로세스는 시스템 운영에 영향을 주지 않도록 설계되었지만 다른 절차는 제한할 수 있습니다. 일반적으로 그리드 노드를 제거하기 전에 계획된 시스템 업그레이드 또는 확장을 수행해야 합니다.
* 특정 단계에서 스토리지 노드를 포함하는 서비스 해제 절차를 일시 중지하여 필요한 경우 다른 유지 보수 절차를 실행하고 작업이 완료되면 재개할 수 있습니다.
* 서비스 해제 작업이 실행 중일 때는 그리드 노드에서 데이터 복구 작업을 실행할 수 없습니다.
* 스토리지 노드를 사용 중단하는 동안에는 ILM 정책을 변경하지 않아야 합니다.
* 스토리지 노드를 제거하면 노드의 데이터가 다른 그리드 노드로 마이그레이션되지만 이 데이터는 사용 중지된 그리드 노드에서 완전히 제거되지 않습니다. 데이터를 영구적으로 안전하게 제거하려면 서비스 해제 절차가 완료된 후 사용 중지된 그리드 노드의 드라이브를 지어야 합니다.
* 스토리지 노드를 서비스 해제할 때 다음과 같은 경고 및 경보가 발생할 수 있으며 관련 e-메일 및 SNMP 알림을 받을 수 있습니다.
+
** * 노드 * 경고와 통신할 수 없습니다. 이 알림은 ADC 서비스를 포함하는 스토리지 노드를 서비스 해제할 때 트리거됩니다. 서비스 해제 작업이 완료되면 경고가 해결됩니다.
** VSTU(Object Verification Status) 알람. 이 알림 레벨 알람은 서비스 해제 프로세스 중에 스토리지 노드가 유지보수 모드로 전환됨을 나타냅니다.
** Casa(Data Store Status) 알람. 이 주요 레벨 알람은 서비스가 중지되었기 때문에 Cassandra 데이터베이스가 작동 중지되었음을 나타냅니다.




.관련 정보
link:restoring-object-data-to-storage-volume.html["오브젝트 데이터를 스토리지 볼륨으로 복원합니다"]
