---
permalink: maintain/decommissioning-disconnected-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, connected nodes, decommission node, storage node, disconnected storage node 
summary: 스토리지 노드의 접속이 끊어지는 동안 스토리지 노드의 서비스를 해제할 경우 어떤 일이 발생할지 이해해야 합니다. 상태는 Unknown 또는 Administratively Down\ 입니다. 
---
= 연결이 끊긴 스토리지 노드의 서비스 해제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 접속이 해제된 상태에서 스토리지 노드의 서비스를 해제할 경우 발생할 수 있는 상황을 파악해야 합니다(상태는 알 수 없음 또는 관리상 중단).

그리드에서 연결이 끊긴 스토리지 노드를 폐기하는 경우 StorageGRID는 다른 스토리지 노드의 데이터를 사용하여 연결이 끊긴 노드에 있던 오브젝트 데이터 및 메타데이터를 재구성합니다. 서비스 해제 프로세스가 끝나면 데이터 복구 작업을 자동으로 시작합니다.

분리된 스토리지 노드를 폐기하기 전에 다음 사항에 유의하십시오.

* 연결이 끊어진 노드를 온라인 상태로 만들거나 복구할 수 없는 경우가 아니면 이 노드를 사용 중단해서는 안 됩니다.
+

IMPORTANT: 노드에서 오브젝트 데이터를 복구할 수 있다고 생각되면 이 절차를 수행하지 마십시오. 대신 기술 지원 부서에 문의하여 노드 복구가 가능한지 확인하십시오.

* 연결이 끊긴 스토리지 노드에 개체의 복사본만 포함되어 있는 경우 노드를 서비스 해제할 때 해당 개체가 손실됩니다. 데이터 복구 작업은 현재 연결된 스토리지 노드에 하나 이상의 복제된 복사본 또는 충분한 삭제 코딩 조각이 있는 경우에만 오브젝트를 재구성 및 복구할 수 있습니다.
* 연결이 끊긴 스토리지 노드를 폐기하면 서비스 해제 절차가 비교적 빠르게 완료됩니다. 그러나 데이터 복구 작업을 실행하는 데 며칠 또는 몇 주가 걸릴 수 있으며 서비스 해제 절차를 통해 모니터링되지 않습니다. 이러한 작업을 수동으로 모니터링하고 필요에 따라 다시 시작해야 합니다. 을 참조하십시오 link:checking-data-repair-jobs.html["데이터 복구 작업을 확인합니다"].
* 연결이 끊긴 스토리지 노드를 한 번에 두 개 이상 폐기하는 경우 데이터가 손실될 수 있습니다. 오브젝트 데이터, 메타데이터 또는 삭제 코딩 단편의 복사본이 너무 적은 경우에도 데이터를 재구성하지 못할 수 있습니다.
+

IMPORTANT: 복구할 수 없는 스토리지 노드가 두 개 이상 연결되어 있는 경우 기술 지원 부서에 문의하여 최상의 조치를 취하십시오.


