---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: '사용 중지 후에도 관리 도메인 컨트롤러\(ADC\) 서비스가 너무 적게 남아 있는 경우 데이터 센터 사이트에서 특정 스토리지 노드의 사용을 중지하지 못할 수 있습니다. 일부 스토리지 노드에서 찾을 수 있는 이 서비스는 그리드 토폴로지 정보를 유지하고 그리드에 구성 서비스를 제공합니다. StorageGRID 시스템은 각 사이트에서 항상 사용할 수 있는 ADC 서비스 쿼럼을 필요로 합니다.' 
---
= ADC 쿼럼을 이해합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용 중지 후에도 너무 적은 ADC(관리 도메인 컨트롤러) 서비스가 남아 있는 경우 데이터 센터 사이트에서 특정 스토리지 노드의 사용을 중지하지 못할 수 있습니다. 일부 스토리지 노드에서 찾을 수 있는 이 서비스는 그리드 토폴로지 정보를 유지하고 그리드에 구성 서비스를 제공합니다. StorageGRID 시스템은 각 사이트에서 항상 사용할 수 있는 ADC 서비스 쿼럼을 필요로 합니다.

노드를 제거하면 ADC 쿼럼이 더 이상 충족되지 않는 경우 스토리지 노드를 해제할 수 없습니다. 사용 중단 중에 ADC 쿼럼을 만족시키려면 각 데이터 센터 사이트의 최소 3개의 스토리지 노드에 ADC 서비스가 있어야 합니다. 데이터 센터 사이트에 ADC 서비스가 있는 스토리지 노드가 3개 이상 있는 경우 이러한 노드 중 단순한 대부분은 사용 중단 후(0.5 *) 사용할 수 있어야 합니다 `_Storage Nodes with ADC_`) + 1).

예를 들어 데이터 센터 사이트에 현재 ADC 서비스가 있는 6개의 스토리지 노드가 있고 3개의 스토리지 노드를 폐기하려는 경우를 가정해 보겠습니다. ADC quorum 요구 사항으로 인해 다음과 같이 2개의 서비스 해제 절차를 완료해야 합니다.

* 첫 번째 서비스 해제 절차에서는 ADC 서비스가 있는 스토리지 노드 4개를 사용할 수 있는지 확인해야 합니다((0.5 * 6) + 1). 즉, 처음에 2개의 스토리지 노드만 서비스 해제할 수 있습니다.
* 두 번째 서비스 해제 절차에서 세 번째 스토리지 노드를 제거할 수 있습니다. ADC 쿼럼은 이제 세 개의 ADC 서비스만 사용할 수 있어야 하므로((0.5 * 4) + 1) 세 번째 스토리지 노드를 제거할 수 있습니다.


스토리지 노드를 해제해야 하지만 ADC 쿼럼 요구 사항으로 인해 해제할 수 없는 경우 확장에서 새 스토리지 노드를 추가하고 ADC 서비스를 사용하도록 지정해야 합니다. 그런 다음 기존 스토리지 노드를 서비스 해제할 수 있습니다.

.관련 정보
link:../expand/index.html["그리드를 확장합니다"]
