---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 스토리지 노드를 추가한 후 EC 재조정 절차를 사용하여 기존 스토리지 노드와 새 스토리지 노드 간에 삭제 코딩 조각을 재배포할 수 있습니다. 
---
= 스토리지 노드를 추가한 후 삭제 코딩 데이터의 균형을 재조정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 추가한 후 EC 재조정 절차를 사용하여 기존 스토리지 노드와 새 스토리지 노드 간에 삭제 코딩 조각을 재배포할 수 있습니다.

.시작하기 전에
* 새 스토리지 노드를 추가하는 확장 단계를 완료했습니다.
* 을(를) 검토했습니다 link:considerations-for-rebalancing-erasure-coded-data.html["삭제 코딩 데이터의 재조정에 대한 고려사항"].
* 복제된 오브젝트 데이터는 이 절차에 의해 이동되지 않으며 EC 재조정 절차에서는 삭제 코딩 데이터를 이동할 위치를 결정할 때 각 스토리지 노드에서 복제된 데이터 사용을 고려하지 않는다는 점을 이해합니다.
* 을(를) 보유하고 있습니다 `Passwords.txt` 파일.


.이 절차를 실행하면 어떻게 됩니까
절차를 시작하기 전에 다음 사항에 유의하십시오.

* 하나 이상의 볼륨이 오프라인 상태(마운트 해제)이거나 온라인 상태(마운트)이지만 오류 상태인 경우 EC 균형 조정 절차가 시작되지 않습니다.
* EC 재조정 절차는 많은 양의 스토리지를 임시로 예약합니다. 스토리지 알림이 트리거될 수 있지만 재조정이 완료되면 문제가 해결됩니다. 예약 저장 공간이 충분하지 않으면 EC 재조정 절차가 실패합니다. EC 재조정 절차가 완료되면 절차가 실패했는지 여부에 관계없이 스토리지 예약이 해제됩니다.
* EC 균형 조정이 진행 중인 동안 볼륨이 오프라인 상태가 되거나 오류가 발생하면 균형 조정 프로세스가 부분적으로 완료되어 데이터가 손실되지 않습니다. EC 균형 조정 절차는 모든 볼륨이 오류 없이 온라인 상태일 때 종료된 지점에서 다시 시작할 수 있습니다.
* EC 재조정 절차가 실행 중인 경우 ILM 작업 및 S3 및 Swift 클라이언트 작업의 성능에 영향을 미칠 수 있습니다.
+

NOTE: EC 재조정 절차 중에 완료하는 데 24시간 이상이 필요한 경우 S3 및 Swift API 작업으로 오브젝트(또는 오브젝트 부분)가 업로드되지 않을 수 있습니다. 해당 ILM 규칙이 수집 시 균형 또는 엄격 배치를 사용하는 경우 장기 PUT 작업이 실패합니다. 다음 오류가 보고됩니다. `500 Internal Server Error`.



.단계
. [[review_object_storage]] 재조정할 사이트의 현재 오브젝트 스토리지 세부 정보를 검토합니다.
+
.. 노드 * 를 선택합니다.
.. 사이트에서 첫 번째 스토리지 노드를 선택합니다.
.. Storage * 탭을 선택합니다.
.. 커서를 Storage Used-Object Data 차트 위에 놓으면 스토리지 노드에서 복제된 데이터의 현재 양과 삭제 코딩 데이터를 볼 수 있습니다.
.. 사이트에서 다른 스토리지 노드를 보려면 다음 단계를 반복합니다.


. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_primary_Admin_Node_IP_`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



. 절차를 시작합니다.
+
`rebalance-data start --site "_site-name_"`

+
용 `"_site-name_"`에서 새 스토리지 노드를 추가한 첫 번째 사이트를 지정합니다. 영역 추출 `site-name` 따옴표로 묶습니다.

+
EC 재조정 절차가 시작되고 작업 ID가 반환됩니다.

. 작업 ID를 복사합니다.
. EC 재조정 절차의 상태를 모니터링합니다.
+
** 단일 EC 재조정 절차의 상태를 보려면
+
`rebalance-data status --job-id _job-id_`

+
용 `_job-id_`에서 절차를 시작할 때 반환된 ID를 지정합니다.

** 현재 EC 재조정 절차 및 이전에 완료된 절차의 상태를 보려면
+
`rebalance-data status`

+
[NOTE]
====
rebalance-data 명령에 대한 도움말을 보려면 다음을 수행합니다.

`rebalance-data --help`

====


. 반환된 상태에 따라 추가 단계를 수행합니다.
+
** 상태가 인 경우 `In progress`EC 재조정 작업이 여전히 실행 중입니다. 절차가 완료될 때까지 주기적으로 모니터링해야 합니다.
+
현재 작업의 예상 완료 시간 및 완료 비율을 보려면

+
... 지원 * > * 도구 * > * 메트릭 * 을 선택합니다.
... Grafana 섹션에서 * EC 개요 * 를 선택합니다.
... Grid EC Job Ec Job Estimated Time to Completion * 및 * Grid EC Job Percentage Completed * 대시보드를 확인합니다.


** 상태가 인 경우 `Success`(선택 사항 <<review_object_storage,오브젝트 스토리지 검토>> 사이트에 대한 업데이트된 세부 정보를 봅니다.
+
이제 삭제 코딩 데이터가 사이트의 스토리지 노드 간에 더 균형 있게 균형 있게 조정되어야 합니다.

+
[TIP]
====
다음 메시지가 나타나면 삭제 코딩 데이터가 모두 재조정될 때까지 EC 재조정 절차를 다시 실행하십시오.

`The moves in this rebalance job have been limited. To rebalance additional data, start EC rebalance again for the same site.`

====
** 상태가 인 경우 `Failure`:
+
... 사이트의 모든 스토리지 노드가 그리드에 연결되어 있는지 확인합니다.
... 이러한 스토리지 노드에 영향을 줄 수 있는 알림을 확인하고 해결합니다.
... EC 재조정 절차를 다시 시작합니다.
+
`rebalance-data start –-job-id _job-id_`

... EC 재조정 절차의 상태가 여전히 인 경우 `Failure`, 기술 지원 부서에 문의하십시오.




. EC 균형 조정 절차에서 너무 많은 로드가 생성되는 경우(예: 수집 작업이 영향을 받음) 절차를 일시 중지하십시오.
+
`rebalance-data pause --job-id _job-id_`

. EC 재조정 절차를 종료해야 하는 경우(예: StorageGRID 소프트웨어 업그레이드 수행) 다음을 입력합니다.
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: EC 재조정 절차를 종료할 때 이미 이동된 데이터 조각은 새 위치에 그대로 남아 있습니다. 데이터가 원래 위치로 다시 이동되지 않습니다.

. 둘 이상의 사이트에서 삭제 코딩을 사용하는 경우 영향을 받는 다른 모든 사이트에 대해 이 절차를 실행합니다.

